### ISSUE TITLE
Default Palettes can not be deleted/renamed

### ISSUE THREAD

**Issue by haythamnikolaidis** [Orama-Interactive/Pixelorama#1010]
**Pixelorama version:**
1.0-dev (main branch)

**OS/device including version:**
Replicated in MacOS 13.x and Windows 10

**Issue description:**
When Pixelorama starts-up, it check if the default palettes exist in the `user://` directory, if they do not exist it will copy them over. It does this check on every start up, therefore if one of the default palettes are delete or renamed on next start up, Pixelorama will copy the missing palettes over again.

**Steps to reproduce:**
1. Start Pixelorama
2. Rename the default palette to default-1
3. Restart Pixelorama
4. Palette list now contains both default and default-1 palettes.

**Comment by Variable-ind** [comment]
Why not "move" the default palettes over instead of copying?

**Comment by OverloadedOrama** [comment]
> Why not "move" the default palettes over instead of copying them over?

I don't think we need to move or copy them at all. Brushes and patterns are not being copied or moved, I think palettes should be the same. Moving them might confuse users who add palettes into `pixelorama_data` and they suddenly see them disappear.

**Comment by OverloadedOrama** [comment]
Should be fixed in https://github.com/Orama-Interactive/Pixelorama/commit/aa47a47b3cce5a85e2594ace0b54d5a6325b296c, palettes should no longer be copied in `user://`.
