### ISSUE TITLE
Switch Left and Right Colours shortcut activating when it shouldn't

### ISSUE THREAD

**Issue by BusOfSelfDoubt** [Orama-Interactive/Pixelorama#1014]
**Pixelorama version:**
v0.11.3

**OS/device including version:**
Windows 11

**Issue description:**
When switch left and right colours shortcut is set to [letter] and any other shortcut is set to [ctrl + letter], the colours will swap whenever pressing [ctrl + letter}. For example, the preset shortcuts has [ctrl + X] as cut, and [X] as swap left and right colours. Whenever you use cut, the colours will swap.

**Steps to reproduce:**
Set switch left and right colours shortcut to any key, then set any other shortcut to ctrl + that key. Then press ctrl + that key.

**Comment by OverloadedOrama** [comment]
This should be fixed in version 1.0.
