### ISSUE TITLE
Shading tool Hue Shifting should allow for negative values

### ISSUE THREAD

**Issue by Srekel** [Orama-Interactive/Pixelorama#1015]
**Pixelorama version:**
0.11.4-stable

**OS/device including version:**
Windows 11

**Issue description:**
With the shading tool, the Hue and Value numbers change as expected when using Lighten and Darken, in that they both add and subtract. Saturation only adds however, even in Darken mode. I *think* that's a straight up bug.

However, for Hue, it would definitely make sense to be able to specify a negative value. In my case I have some grass, and where it's in shadow beneath trees, I'd like it to be darker ✅, I'd like the saturation to go down 🐞 , and, I'd also like it to be tinted a bit towards brown, i.e. go "up" on the hue scale. 

So I think a more comprehensive solution would "simply" be to make the sliders go in the positive and negative. 

(If you do this you wouldn't *really need* to keep lighten and darken as separate options, but honestly it's still quite useful to be able to just flip that and keep painting, rather than change the Value slider from say -10 to 10. )

**Comment by OverloadedOrama** [comment]
In hue shifting mode, saturation is supposed to decrease when brightening and increase when darkening, as explained here https://www.oramainteractive.com/Pixelorama-Docs/user_manual/shading#hue-shifting

Sliders going negative sounds good to me, I implemented it in d734ae24a5dce6b17cca7c7e401918f899b91039 and it will be available for version 1.0. Thank you for the suggestion!

**Comment by Srekel** [comment]
Cool, impressive how fast you fixed it! :)
