### ISSUE TITLE
Saveing on Programm closeing saves unsaved project into the wron file

### ISSUE THREAD

**Issue by HobTheGoblin** [Orama-Interactive/Pixelorama#1029]
**Pixelorama version:**
0.11.4-stable

**OS/device including version:**
Windows 11

**Issue description:**
When i closed Pixelorama it saved the wrong project and overrided the my file. The original data gets lost.

**Steps to reproduce:**
- open new project
- draw a yellow circle
- save yellow circle as file "yellow.pxo"
- while first project is still open, create another project
- draw a red circle
- close pixelorama
- choose "save and exit"
- cancel the save dialog>pixelorama stays open
- select your first project with the yellow cirle
- ctrl+s / save
- pixelorama will close
- open file a.pxo
- its the red cirlce

**Comment by Variable-ind** [comment]
Hy, this bug was fixed a few weeks ago, could you check the nightly build and verify it?

Nightly: https://nightly.link/Orama-Interactive/Pixelorama/workflows/dev-desktop-builds/master

**Comment by HobTheGoblin** [comment]
Hi,
this issue is not reproducible on the master.
