### ISSUE TITLE
Issues with some dropdown menus and check boxes

### ISSUE THREAD

**Issue by FrozenGamer1640** [Orama-Interactive/Pixelorama#1036]
**Pixelorama version:**
0.11.4 - stable (From Snap Store)

**OS/device including version:**
Ubuntu 22.04.4 LTS

**Issue description:**
When you click on some menus it "remain selected", and if you press the spacebar (default pan key) you "activate" them as they would using a gamepad or similar.

**Steps to reproduce:**
select a dropdown menu with the mouse, and try to use the spacebar
[Grabación de pantalla desde 16-07-2024 08:46:32.webm](https://github.com/user-attachments/assets/1f905a4e-9914-4657-8e9d-91030a037b19)

**Extra notes:**
> Sorry for my grammar, I'm still learning English
- There are no extensions enabled rather than "Key Display"
- This issue doesn't happen everywhere

**Comment by Variable-ind** [comment]
Hy 👋, thanks for reporting, this issue has been fixed in V1.0 (https://github.com/Orama-Interactive/Pixelorama/commit/b4384f4085ef451f0ac8a3a8a1fb4ccadef2e0cb)

You could try the nightly build here: https://nightly.link/Orama-Interactive/Pixelorama/workflows/dev-desktop-builds/master
