### ISSUE TITLE
Simple window mode breaking ability to change settings back.

### ISSUE THREAD

**Issue by Blanquefort-bq** [Orama-Interactive/Pixelorama#1054]
**Pixelorama v1.0-stable**

**Windows 11 23H2**

**Issue description:**
after disabling "Single window mode" in Preferences/Interface and restarting the program, makes us unable to change any settings in preferences.

**Steps to reproduce:**
1. Open Pixelorama
2. Edit/Preferences/Interface/Single window mode turn to off
3. Restart program
4. Open program again
5. Edit/Preferences (now you cant click/do anything in Preferences window

**Comment by Variable-ind** [comment]
Hy, thanks for reporting you can restore your window setting by deleting `override.cfg` file located in the same place as pixelorama.exe

**Comment by Blanquefort-bq** [comment]
it does! Thx
