### ISSUE TITLE
Unable to save project with blended images on KDE

### ISSUE THREAD

**Issue by ChiliEater** [Orama-Interactive/Pixelorama#1058]
**Pixelorama version:** 1.0

**OS/device including version:**
- Arch Linux
- Flatpak version
- KDE Plasma 6.1 (Wayland)

**Issue description:**
[According to the documentation](https://www.oramainteractive.com/Pixelorama-Docs/concepts/project#include-blended-images), it should be possible to save projects with blended images included. I assume this works when not using the native file picker. On KDE, this option is not available and I couldn't find a way to either change this setting or disable the native file picker.

![image](https://github.com/user-attachments/assets/7809e724-f7ee-465b-bd55-aea45b40cabb)

**Steps to reproduce:**
- Create project
- Save file as...
- "Include blended images" is not available

Congrats on the 1.0 release!

**Comment by OverloadedOrama** [comment]
Hello, and thank you! This is indeed a known limitation of native file dialogs, but it will be fixed once Godot 4.3 is out. Normally you can disable the native file dialogs from the Preferences, but if you are using the Flatpak version this isn't possible because it sandboxed.

**Comment by ChiliEater** [comment]
Thanks for the quick reply. I'll try the AUR package then.
