### ISSUE TITLE
KDE Plasma treats Pixelorama as one of Godot's windows when they're both open

### ISSUE THREAD

**Issue by PopeRigby** [Orama-Interactive/Pixelorama#106]
# Description
When Godot is opened, and then Pixelorama is opened, KDE Plasma treats Pixelorama as one of Godot's windows. This only happens when Godot is opened first. 

# Steps to Reproduce
1. Open Godot
2. Open Pixelorama

# Behavior
In the taskbar, Godot will have a green plus on its icon, meaning that there are multiple windows open under Godot. 
![image](https://user-images.githubusercontent.com/20866468/71758178-6f22c600-2e51-11ea-9533-ecf3ef40a89c.png)
Clicking on the Godot icon gives me the option to either bring the Godot window or the Pixelorama window to the foreground.

# Expected Behavior
Pixelorama is treated as it's own application.

# Additional Information
* Godot version: 3.1.2.stable.flathub
* Pixelorama version: 0.5
* KDE Plasma version: 5.17.4

**Comment by Calinou** [comment]
This is strange… [Godot sets the window manager class to the application name](https://github.com/godotengine/godot/pull/22733), so this shouldn't happen in the first place.

Does this happen with a non-Flatpak build of the Godot editor?

**Comment by PopeRigby** [comment]
> Does this happen with a non-Flatpak build of the Godot editor?

Yes, it does.

**Comment by OverloadedOrama** [comment]
Does this happen with other Godot projects as well, or only Pixelorama? If this is a Godot issue, you should try opening an issue on Godot's GitHub repository.

**Comment by PopeRigby** [comment]
I'm not familiar with many Godot projects. Could you give me one I can try?

**Comment by Calinou** [comment]
@PopeRigby Here are a few ones:

- https://github.com/RodZill4/godot-procedural-textures
- https://github.com/Calinou/escape-space
- https://github.com/Alzter/TuxBuilder

**Comment by Schweini07** [comment]
JUst a question of interest @PopeRigby.. what distro are you using?

**Comment by PopeRigby** [comment]
ArchLinux

**Comment by PopeRigby** [comment]
@Calinou [Material Maker](https://github.com/RodZill4/godot-procedural-textures) seems to do the same thing.

**Comment by PopeRigby** [comment]
I've opened an [issue](https://github.com/godotengine/godot/issues/34895) in the Godot repository.

**Comment by Sslaxx** [comment]
From the sound of it, it might be worth filing an issue on KDE's trackers.

**Comment by novhack** [comment]
This is not an issue with Pixelorama or Godot but something with your KDE setup. I have Plasma 5.18.4.1 on EndeavourOS (Arch based) and I could not recreate the problem.
![Screenshot_20200501_031823](https://user-images.githubusercontent.com/42614907/80773553-8735f800-8b5a-11ea-8a1c-f570bd27e43f.png)
I would personally close this issue as not relevant to Pixeloramas codebase.
