### ISSUE TITLE
Extra mouse buttons do not function when used as shortcuts

### ISSUE THREAD

**Issue by Violet-RM** [Orama-Interactive/Pixelorama#1070]
**Pixelorama version:**

1.0.1-stable, specifically the flatpak

**OS/device including version:**

Linux Mint 22

**Issue description:**

When setting my shortcuts to my liking, I want to set undo and redo to mouse4 and mouse5, called mouse thumb button 1 and 2 in the settings. To clarify, I am not trying to edit the default bindings, and I am able to set other shortcuts (ex: i set Ctrl-Alt-Shift-1 just to see if i was doing something wrong when setting shortcuts in the first place, and it worked as expected). I only encounter this issue when I am setting a binding to side mouse buttons.

**Steps to reproduce:**
1. Set a shortcut to a mouse thumb button
2. The shortcut is not executed when using the mouse thumb button and nothing happens

**Comment by Violet-RM** [comment]
Still an issue in the 1.0.3 release

**Comment by OverloadedOrama** [comment]
This is a Godot bug, it happens with other Godot projects. I opened an issue to its repository: https://github.com/godotengine/godot/issues/98057

**Comment by OverloadedOrama** [comment]
I implemented a workaround myself in 6863adf957adb0d218bd078e9700ace101cd4312 because I'm unsure if and when this will be addressed in Godot's side. If it is, I will remove the workaround. The fix will be in the next stable version, thank you for reporting!
