### ISSUE TITLE
OmniScale/CleanEdge Scaling issues

### ISSUE THREAD

**Issue by ShadowFungi** [Orama-Interactive/Pixelorama#1074]
**Pixelorama version:**
1.0.1 and commit 9c170ee5a02984537780766c23f4038e3875afb1 also attempted on itch.io web build

**OS/device including version:**
Arch Linux native, and FlatPak with Nvidia GTX 1050 Ti mobile

**Issue description:**
OmniScale, and CleanEdge scaling only grabs top left pixel of image for scaling

**Steps to reproduce:**

1. Open the scale image menu.
2. Set interpolation to OmniScale, or CleanEdge.
3. Set Width/Height to a value other than the original size
4. Press 'OK'

**Comment by OverloadedOrama** [comment]
Good catch, thanks! Should be fixed by 3113459224232f9ad51ef10abb12c22c28a8676a.

**Comment by ShadowFungi** [comment]
Indeed it has been fixed, no problem, and thank you
