### ISSUE TITLE
Suggestion: ask to confirm when the user creates a new blank image while there is one not saved in background

### ISSUE THREAD

**Issue by Gaarco** [Orama-Interactive/Pixelorama#109]
At the moment when you create another image it doesn't ask to confirm and if I have something not saved in background all the work will be lost.
I suggest to open a yes or no dialog to confirm the action, or implement multiple tabs, one for each canvas

**Comment by OverloadedOrama** [comment]
Hello! We plan to implement multiple tabs in v0.7, as well as a dialog to confirm whether you are sure you want to remove the tab, if you have unsaved progress!

**Comment by OverloadedOrama** [comment]
Tabs have now been implemented, and will be included in Pixelorama v0.8. Every time the user creates a new image or loads a project, a new tab is being created, that lets the user easily switch between projects.
![image](https://user-images.githubusercontent.com/35376950/84213661-eed05300-aac9-11ea-902c-043fb52a74d3.png)
