### ISSUE TITLE
SHA256 isn't matching after the update

### ISSUE THREAD

**Issue by Ars888** [Orama-Interactive/Pixelorama#1092]
The actual sum should be: e8ae206f3757d3386ab5c62c1d76fc7aba728c73276c2a74cbd992e0486c0112

Tried to download pixelorama(v1.0.2) on mac using brew, and "Error: SHA256 mismatch" popped up

**Comment by V-Weitemeyer** [comment]
still there

**Comment by OverloadedOrama** [comment]
Closing as this shouldn't be a problem anymore now that v1.0.3 is out.
