### ISSUE TITLE
Hold "Spacebar" to pan viewport

### ISSUE THREAD

**Issue by Mainman002** [Orama-Interactive/Pixelorama#110]
Not really a bug more like a feature request. The middle mouse button works alright but can be tiring when using a mouse. I find in other painting apps that holding the Spacebar to pan can help reduce mouse clicking fatigue. 

(this being said idk if the Spacebar is being used / will be used in other features, but it would be nice to have alternative keymaps for panning)

**Comment by OverloadedOrama** [comment]
Hello! I like this idea, this will most likely be added in v0.7. I also want to add scroll sliders to the canvas, when the user has zoomed in, in order to move the viewport, but I'm still not sure how to go with this yet.

**Comment by OverloadedOrama** [comment]
A (positive) change of plans. I'm preparing a v0.6.1 release, which is expected to release within a few days. This suggestion will be included in v0.6.1, instead of v0.7!

**Comment by Mainman002** [comment]
Oh Wow SWEET!! thank you! :)
