### ISSUE TITLE
.gpl palettes are not imported correctly

### ISSUE THREAD

**Issue by Gaarco** [Orama-Interactive/Pixelorama#112]
I've tried only with .gpl palettes and I noticed that some colors are not imported correctly

**Comment by OverloadedOrama** [comment]
Hello. Can you explain what you mean by "not imported correctly"? Are the colors different than the ones in the .gpl file? It would be even more helpful if you could give a .gpl file as an example of the issue. :)

**Comment by Gaarco** [comment]
The colors are different (from what I experienced only the darkest color of the palette), if I try for example to import [this palette](https://lospec.com/palette-list/rustic-gb) the colors should be:
[2c2137, 764462, edb4a1, a96868] but what I got in Pixelorama is: [2c0300, 764408, edb4a1, a96868].
I don't know if it's related but the substring missing from the "wrong colors" is usually inside the "color name" label: example, for color 2c0300 in the label there is the missing part 2137 and for color 764408 there is 64462

**Comment by Gaarco** [comment]
I've also tried with other palettes and some colors are always different.
Tested with these:
https://lospec.com/palette-list/truegb
https://lospec.com/palette-list/dirtyboy
https://lospec.com/palette-list/nostalgia
https://lospec.com/palette-list/1bit-monitor-glow

**Comment by OverloadedOrama** [comment]
I found the issue. Some .gpl files were separating the color values with `tab` and not spaces. Will commit fix shortly. Thanks!
