### ISSUE TITLE
Request : Do not remember the last exported name but use the .pxo name.

### ISSUE THREAD

**Issue by kakoeimon** [Orama-Interactive/Pixelorama#114]
Pixelorama remembers exported values and this is great, but it remembers and the last exported name.
I think for the name it will be better if the name of the prohect (.pxo) is used.

**Comment by OverloadedOrama** [comment]
Hello! I'm not entirely sure what you mean by this. Are you suggesting that, if you have saved a `.pxo` file with a certain name, then this name should be remember for exporting the `.png` file?

**Comment by kakoeimon** [comment]
Yes, if you save or load a .pxo file.
For example i work on a image and I save it as img_1.pxo then I click export and the img_1 will be the default name for the export (right now if it is the first time I export defaul name will be empty)
Then I create a new image and save it as img_2.pxo, if I click export the default name will be img_2 (right not it remembers img_1)

**Comment by OverloadedOrama** [comment]
Okay I see, I like this idea! I will implement it shortly :)
