### ISSUE TITLE
Color value 7 converts to value 6 if exported as png and alpha value is 155

### ISSUE THREAD

**Issue by Rajala1404** [Orama-Interactive/Pixelorama#1155]
**Pixelorama version:**

4.3.stable.official.77dcf97d8 (1.0.5)

**Where did you download Pixelorama from?**

AUR (pixelorama-bin)

**OS/device including version:**

OS: Arch Linux x86_64
GPU: AMD Radeon RX 6800

**Issue description:**

If I export any Pixelorama Project as png and the pixel has a color value of 7 that color value turns on the PNG to 6.
That only happens to pixels with a alpha value of 155. 
That's the weirdest Bug I have ever seen is that some kind of float magic?

**Steps to reproduce:**
1. Draw a Pixel with an alpha of 155 and some other value of 7.
2. Export that project as PNG and check the pixel in the PNG with Pixelorama or some other tool and the value of 7 changed to 6

**Comment by BrotherShort** [comment]
I reproduced the bug on Windows, and find out the key code.
It happened here:
![image](https://github.com/user-attachments/assets/126dd08b-cecf-4727-9a82-6c14b7ed3ac5)
It seems like that `blend_rect` function outputs an exception result.
I tested the function alone.
```
	var image = Image.create(256, 256, false, Image.Format.FORMAT_RGBA8);
	var blended = Image.create(256, 256, false, Image.Format.FORMAT_RGBA8);
	blended.set_pixel(0,0, Color(7 * 1.0 / 255, 7 * 1.0 / 255, 7 * 1.0 / 255, 155 * 1.0 / 255));
	image.set_pixel(0, 0, Color(0, 0, 0, 0));

	image.blend_rect(blended, Rect2i(Vector2i.ZERO, Vector2i(256,256)), Vector2i.ZERO)

	print(blended.get_pixel(0, 0));
	print(image.get_pixel(0, 0));
```
Then get the same result.
```
(0.0275, 0.0275, 0.0275, 0.6078)
(0.0235, 0.0235, 0.0235, 0.6078)
```
Unfortunately, it is upstream Godot's bug.

**Comment by BrotherShort** [comment]
The bug not only happens in exporting png, but also happens in exporting webp, scaling canvas... everywhere using blend layers

**Comment by BrotherShort** [comment]
I viewed Godot code, and find this:
```
		case FORMAT_RGBA8: {
			ptr[ofs * 4 + 0] = uint8_t(CLAMP(p_color.r * 255.0, 0, 255));
			ptr[ofs * 4 + 1] = uint8_t(CLAMP(p_color.g * 255.0, 0, 255));
			ptr[ofs * 4 + 2] = uint8_t(CLAMP(p_color.b * 255.0, 0, 255));
			ptr[ofs * 4 + 3] = uint8_t(CLAMP(p_color.a * 255.0, 0, 255));

		} break;
```
Color data in program is float. Using uint8_t(...) to convert float to int, fractional part is discarded, so the color data changed.
There is a Godot issue about it. godotengine/godot#59983
We should wait Godot fixs it.

**Comment by Rajala1404** [comment]
Oh ok. But I like how that issue is fricking 3 years old
