### ISSUE TITLE
Left tool drawing preview is not visible when right tool has preview

### ISSUE THREAD

**Issue by kazardous** [Orama-Interactive/Pixelorama#1157]
**Pixelorama version:**

Tested on https://github.com/Orama-Interactive/Pixelorama/commit/033238b7873c22a7ca9b96b8f2779fd7f390b93c and v1.0.5-stable

**Where did you download Pixelorama from?**

Github

**OS/device including version:**

Tested on Debian 12 and Windows 10

**Issue description:**

I selected two tools that show a drawing preview on both left and right click, e.g. Line tool and Lasso, and the left tool drawing preview is not visible when drawing as would be expected. Only the right tool drawing preview is visible when drawing.

![line-and-lasso](https://github.com/user-attachments/assets/46c15801-1fb9-4415-88a5-6641a7383a03)

This bug seems to affect any line, shape, or selection tool that has a drawing preview, the only exception is the rectangular selection tool, which behaves as expected.

Affected tools:
- Elliptical Selection
- Polygonal Selection
- Lasso / Free Select Tool
- Select by Drawing
- Line Tool
- Curve Tool
- Rectangle Tool
- Ellipse Tool

Examples with selecting the same tool on left/right and using left tool, then right tool:
![select-tools](https://github.com/user-attachments/assets/ca56bede-d529-4e7b-9335-f496f0208f7f)
![lines-and-shapes](https://github.com/user-attachments/assets/dddb3c7c-6ca9-489e-ab7e-8bd62b97ec48)

**Steps to reproduce:**
- Select any of the listed affected tools above as both left and right click tools, e.g. Line tool on left, Lasso on right
- Draw on the canvas with the left tool and the drawing preview will not be visible

**Comment by kazardous** [comment]
This can be fixed with a (quick and dirty) check on draw preview. I've done this [here](https://github.com/Orama-Interactive/Pixelorama/commit/f99f7a101e0012fd4a7de3c7a2e78b5904873e62) but this was before I realized the select tools are affected and the rectangular selection tool is an exception to this bug. So I haven't started a PR with this change yet to look at how rectangular selection handles it.

**Comment by OverloadedOrama** [comment]
Thank you so much for finding the bug! I had gotten reports that the tool preview was sometimes not being shown and I had no idea what caused it. I suppose this must be the root of the issue. I believe 59254b943f1c59f322c50339d0ff5a0f5e3f5ab4 should be enough to fix the issue, hopefully I didn't break anything else.

**Comment by OverloadedOrama** [comment]
My bad, that commit did not fix the issue for all tools. a698668930e3910187ea494a7e1fa5b8ed9f33e4 should now also fix the curve and polygon selection tools.

**Comment by kazardous** [comment]
Amazing! You're very welcome, glad I could help narrow it down. I've just tested this and can confirm this fixes all previews.
