### ISSUE TITLE
Pixelorama snap

### ISSUE THREAD

**Issue by Aury88** [Orama-Interactive/Pixelorama#116]
Hi! 

I saw that someone ( probably @Schweini07  ) already registered the "pixelorama" name in the snap store. This is great! 
I have already a working  snap version of pixelorama 0.6 and I would like to share it with you so you don't have to [waste your time reinventing the wheel](https://forum.snapcraft.io/t/pixelorama-snap-need-help/14962).
[HERE](https://mega.nz/#!oU0EAaQT!pNEDss7pABpmlicHfsjNFJrrI4cED_X_UnOwF_7BhMg) there is the compilable base ready to be snapped with snapcraft .
To test the snap in a linux distro you only have to unzip the file , cd in it and launch `snapcraft` and  `sudo snap install pixelorama_0.6_amd64.snap --dangerous`.
As you can see the ziped file contain only a "files" directory (containing the same files in your [Linux 64-bit].zip download) and a snap directory containing the snapcraft.yaml file.

I hope this will help you share your great app.

Thank you for your great work. 
Regards,
AC
![Snap Pixelorama](https://user-images.githubusercontent.com/3192478/72171804-00ef7d80-33d4-11ea-8a43-ff8586cc184a.png)

**Comment by Schweini07** [comment]
Ah, neat. You made it (not like me who had absolutely no knowledge how to do this). I think I'll delete the repository now.

**Comment by Aury88** [comment]
Hi @Schweini07.
I also have absolutely no knowledge about the snapping process; I was lucky because I had only to follow the [Popey instructions](https://forum.snapcraft.io/t/how-to-create-yaml-for-a-simple-godot-3-engine-project-game-how-to-create-snap/9822) (they seems can be used for any Godot application/game).
If you want you can push the snapcrafted app on the store after a ` snapcraft login` and a `snapcraft push --release=stable pixelorama_0.6_amd64.snap` commands.
I would have done it myself but the pixelorama name can't be used by me so I should have changed the package name and the launch command making it very inconvenient.

**Comment by Schweini07** [comment]
If I delete the repository will you then be able to publish it yourself?

**Comment by Aury88** [comment]
Unfortunately it is not enough. you must also delete the name registration "pixelorama" from the store. but there is still no a direct way to do it. you must request it to the store managers (I think in the forum).

**Comment by OverloadedOrama** [comment]
Hey there. I'm not really familiar with snap, is there anything else that needs to be done? I recently updated Pixelorama to v0.6.1 too. What exactly do we need to do so snap stays up to date?

**Comment by Aury88** [comment]
hi, @OverloadedOrama !
it is possible to stay up to date by built automatically a github source. you have only to follow [this](https://snapcraft.io/build).
but first I fear you should  have to [claim the pixelorama name in the store]( https://snapcraft.io/register-name-dispute?snap-name=pixelorama) and wait for the assignment.

**Comment by Aury88** [comment]
hi  , @Schweini07 ...
today I tried to fill a Name dispute so to upload  the snap with the official name...I don't know if they will accept that because I've not  right on the app name (for example I'm not one of the app developers)

If they accept my requests then I can add collaborations (I don't know what they can do) or, in the future, I can ask in the forum to transfer the snap/name to you  @OverloadedOrama if you have a snap-store account )

**Comment by Schweini07** [comment]
@Aury88 Great work!

A few days ago I asked in the forum if I somehow can delete the 'Pixelorama' name. Sadly with no response.

If you have any instruction in the future how I can transfer the name to you, just message me!

Cheers

**Comment by Aury88** [comment]
hi @Schweini07 
try [this link](https://dashboard.snapcraft.io/register-snap-feedback/pixelorama/.) to confirm you agree to release the snap name...
snapcraft has a very active forum so I fear that posting on the forum can lead to some delay or your message  lost.

**Comment by Schweini07** [comment]
Ok, I sent a message, I'll update you if I get any response

**Comment by Schweini07** [comment]
@Aury88 I got a reply, the name has been transferred!

**Comment by Aury88** [comment]
@Schweini07 thank you!

now [it is on the store](https://snapcraft.io/pixelorama) and anybody can install it through a simple `sudo snap install pixelorama` or by any snap compatible software center
I hope it works.
@OverloadedOrama  I would like to use the app official logo in the store...am I authorized? do you have a svg version?

**Comment by OverloadedOrama** [comment]
Hey @Aury88, we don't have a svg version I'm afraid, but feel free to use `icon.png` if you want, which is 256x256

**Comment by Schweini07** [comment]
@Aury88 I installed Pixelorama trough **sudo snap install --candidate pixelorama** but there's no icon showing up in my app menu. With **pixelorama** it starts but I don't know if it's because the snap or because I have an executable exported from Godot on my laptop.

**Comment by Aury88** [comment]
that is probably due [to a bug like this](https://bugs.launchpad.net/ubuntu/+source/chromium-browser/+bug/1732482) when I  snapcrafted the source 
I just released the revision number 11...I hope it will fix that

**Comment by Aury88** [comment]
added a new banner so to publicize the app in the snap store:
![Selezione_105](https://user-images.githubusercontent.com/3192478/74082672-90805e80-4a5c-11ea-8b9d-14b6f290d948.png)
 I'm not good in graphic arts so, as you can see,  I had to reuse a your screenshot hoping this will be not infringe any copyright/license.

**Comment by Schweini07** [comment]
I tried the new candidate out, it works perfectly, but there's one huge disadvantage towards the Flatpak package. There are no brushes and palettes, I think they are located in the .zip file from itch.io: https://orama-interactive.itch.io/pixelorama

**Comment by Aury88** [comment]
yes I saw that too @Schweini07 , I have to understand how pre-load/install them in the snap.

**Comment by Aury88** [comment]
when I launch the snap the only warning I see is this:
`Godot Engine v3.1.2.stable.official - https://godotengine.org`
`OpenGL ES 2.0 Renderer: Mesa DRI Intel(R) HD Graphics 520 (Skylake GT2) `

`WARNING: _png_warn_function: iCCP: profile 'ICC profile': 'RGB ': RGB color space not permitted on grayscale PNG`

`   At: drivers/png/image_loader_png.cpp:71.`

`WARNING: _png_warn_function: iCCP: profile 'ICC profile': 'RGB ': RGB color space not permitted on grayscale PNG`

`   At: drivers/png/image_loader_png.cpp:71.`

where should the brushes and palette files e located?
the only brushes that works (by default) are these:
![immagine](https://user-images.githubusercontent.com/3192478/74506394-c5c3fb00-4ef9-11ea-8316-859190cac3b9.png)

**Comment by OverloadedOrama** [comment]
@Aury88 The "Brushes" and the "Palettes" folders should be on the same folder as the Pixelorama executable. The "Grass" and "Stars" should be inside "Brushes".

**Comment by Aury88** [comment]
@OverloadedOrama : yes that seems correctly located in the snap:
**/snap/pixelorama/current**$ tree
.
├── bin
│   └── desktop-launch
├── Brushes
│   ├── Brushes
│   ├── circle_blended.png
│   ├── Godot.png
│   ├── Grass
│   │   ├── %Grass1.png
│   │   ├── %Grass2.png
│   │   ├── %Grass3.png
│   │   ├── %Grass4.png
│   │   └── %Grass5.png
│   ├── hline_3x3.png
│   ├── Pixelorama.png
│   ├── Snow.png
│   ├── Star
│   │   ├── %star1.png
│   │   ├── %star2.png
│   │   ├── %star3.png
│   │   ├── %star4.png
│   │   ├── %star5.png
│   │   └── %star6.png
│   └── vline_3x3.png
├── command-pixelorama.wrapper
├── etc
│   ├── drirc
│   ├── pulse
│   │   └── client.conf
│   ├── sensors3.conf
│   └── sensors.d
├── lib
│   └── x86_64-linux-gnu
│       ├── libbsd.so.0 -> libbsd.so.0.8.2
│       ├── libbsd.so.0.8.2
│       ├── libdbus-1.so.3 -> libdbus-1.so.3.14.6
│       ├── libdbus-1.so.3.14.6
│       ├── libexpat.so.1 -> libexpat.so.1.6.0
│       ├── libexpat.so.1.6.0
│       ├── libglib-2.0.so.0 -> libglib-2.0.so.0.4800.2
│       ├── libglib-2.0.so.0.4800.2
│       ├── libjson-c.so.2 -> libjson-c.so.2.0.0
│       ├── libjson-c.so.2.0.0
│       ├── libwrap.so.0 -> libwrap.so.0.7.6
│       └── libwrap.so.0.7.6
├── meta
│   ├── gui
│   │   ├── icon.png
│   │   ├── pixelorama.desktop
│   │   └── pixelorama.png
│   └── snap.yaml
├── Palettes
│   ├── bubblegum16.json
│   ├── Complementary.json
│   ├── Default.json
│   ├── default_palette.json
│   ├── Monochromatic.json
│   ├── Shades.json
│   └── Triad.json
├── **Pixelorama.pck**
├── **Pixelorama.x86_64**
├── snap
│   └── gui
│       ├── pixelorama.desktop
│       └── pixelorama.png
└── usr

are they called through a relative paths or through an absolute paths?

**Comment by OverloadedOrama** [comment]
They're called through relative paths. In v0.6.1 and prior, they were being called with `dir.open(".")`, where the dot means root directory. But in v0.6.2 I changed it to use `OS.get_executable_path().get_base_dir()` instead, because it was not working properly when you were opening Pixelorama from a file. So maybe there is a chance this will also fix the problem?

**Comment by Aury88** [comment]
I honestly don't know xD ... I hoped the missing brushes and palettes was due to an use of absolute path. but in snap we are opening the app from a file so maybe that change will solve the issue.
I'm searching the pixelorama flatpak manifest so to understand how this was solved there

**Comment by OverloadedOrama** [comment]
@Aury88 I released v0.6.2 some days ago, perhaps it will work with this version? Also, looking at [Pixelorama's flatpak repo's yaml file](https://github.com/flathub/com.orama_interactive.Pixelorama/blob/master/com.orama_interactive.Pixelorama.yaml), under **modules** and then **commands**, there's this on line 30:
```
# `cd` is needed so that Pixelorama can find the `Brushes/` directory
          - cd /app/bin/
```
Does this help somehow? Maybe the Brushes and Palettes folders should be placed inside the bin directory?

**Comment by Aury88** [comment]
@OverloadedOrama I don't know but I don't think it will be solved in this way. snaps normally can access only their own  subdirectories. I Will try the new v.0.6.2 asap .
Thank you!

**Comment by Aury88** [comment]
Hi @OverloadedOrama,
your last version  seems to solve the issues in my local install. Impressive job!!!

I've already pushed the last version in the store in the candidate channel.
I need some confirmations if it works correctly also in other OS before promote it on the stable channel :crossed_fingers:

**Comment by Schweini07** [comment]
Pixelorama works now great on snap! I am pretty sure it's now ready to come to the stable channel.

**Comment by Schweini07** [comment]
I think that issue can be closed now!

**Comment by Aury88** [comment]
ps: here the snapcraft.yaml
```

name: pixelorama
base: core18
version: '0.6.2'
summary: Pixelorama sprite editor
description: |
  Free & open-source 2D sprite editor, made by Orama Interactive in the Godot Engine, using GDScript!


icon: snap/gui/pixelorama.png
grade: stable
confinement: strict

apps:
  pixelorama:
    command: desktop-launch "$SNAP/Pixelorama.x86_64"
    environment:
      LD_LIBRARY_PATH: "$LD_LIBRARY_PATH:/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio"
    plugs:
      - opengl
      - network
      - network-bind
      - pulseaudio
      - x11
      - desktop
      - joystick
      - home

parts:
  editor:
    plugin: dump
    source: files/
    after: [desktop-glib-only]
    stage-packages:
      - libgl1-mesa-dri
      - libglu1-mesa
      - libgl1-mesa-glx
      - libpulse0
      - libxcursor1
      - libxinerama1
      - libxrandr2
      - libxi6
      - libasound2
  desktop-glib-only:  
        build-packages:
          - libglib2.0-dev
        plugin: make
        source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
        source-subdir: glib-only
        stage-packages:
          - libglib2.0-bin
```
