### ISSUE TITLE
Choosing destination folder when exporting crashed my application.

### ISSUE THREAD

**Issue by BrancuAlexandru** [Orama-Interactive/Pixelorama#1160]
**Pixelorama version:**

1.0.2 Stable

**Where did you download Pixelorama from?**

Itch.io

**OS/device including version:**

Windows 10 Pro Version 22H2 OS Build 19045.5247
GPU: GT 1030
CPU: i7 3770S @ 3.1GHz
RAM: 12GB DDR3

**Issue description:**

I was choosing the destination for export and it crashed but I only lost 10-20 mins of work thankfully. After a few windows updates and like 2 or 3 months I tried to export and choose destination again, and this time it worked. The windows version and OS build above are my current ones, not the ones from a while back when I had the issue.

**Steps to reproduce:**
Change panel layout moving the pallete and left right brush to the bottom, move the animation timeline to the right under the color picker. Work for a while. Export as > change destination > name > confirm.

**Comment by OverloadedOrama** [comment]
Hello! I am a bit confused, did you have this issue months ago and now it got fixed? Or is it the other way round? If so, we should close the issue as it has been resolved.

**Comment by BrancuAlexandru** [comment]
I had the issue months ago, nothing significant changed since then other than like 2 windows updates. I'm just reporting the crash, you can close it if you want. Also you should probably have some crash logging because I tried to look for logs and couldn't find any.

**Comment by OverloadedOrama** [comment]
I'll go ahead and close the issue then, thanks for reporting! There are logs already, you can find the folder that they are stored in by going to the Help menu and clicking on "Open Editor Data Folder", and then going to the "logs" folder. On Windows, this should be in `C:\Users\[USERNAME]\AppData\Roaming\Pixelorama\logs`
