### ISSUE TITLE
Request: Pick Color with Alt and mouse button.

### ISSUE THREAD

**Issue by kakoeimon** [Orama-Interactive/Pixelorama#125]
Right now the color picker exist only as a separated tool, the request is to be and a tool that leaves inside the Draw tools, Pencil and Bucket and pick colors by holding down the Alt key and pressing the left mouse button for the left color or the right mouse button for the right color.
This will improve the workflow tremendously and possible this is the reason that almost all the drawing apps have something similar.

**Comment by novhack** [comment]
I would strongly advice against using Alt+mouse combination anywhere because that is what most Linux DEs use to manipulate windows.

**Comment by Calinou** [comment]
@novhack Unfortunately, we may not have a choice if other mouse combinations are already taken. Maybe using <kbd>Alt + Shift + mouse</kbd> could work out of the box on Linux, but it's also more tedious.

**Comment by novhack** [comment]
Couldn't `Ctrl + mouse` be used? I haven't found any other combination where `Ctrl + mouse` is used other than when combined with `Shift` to draw lines at certain angles. Or am I missing a hidden feature?

**Comment by Ryhon0** [comment]
I added this feature to [my fork](https://github.com/ryhon0/pixelorama). When you hold `Ctrl + mouse` it sets the left or right color depending on what button you pressed to whatever is under your cursor. I just copied the color picker code and checked if user is holding Ctrl. It's not the best code, but it works

**Comment by Wishdream** [comment]
Why not just allow people to reassign `Shift`, `Alt` and `Ctrl` on tool use?
I'm on Linux, and I basically moved my `Alt` to `Meta` for moving windows.

Say like `Shift` is Alt. Tool Mode.

Similar to Krita's Canvas Input Settings:
![image](https://user-images.githubusercontent.com/4660711/81116195-85ec3d00-8f57-11ea-9dd3-2779c247e069.png)

**Comment by vlandemart** [comment]
I wrote my ideas in #508

**Comment by OverloadedOrama** [comment]
The ability to pick colorswhile holding <kbd>Alt</kbd> while a drawing tool is selected (Pencil, Eraser, Shading, Bucket, Line, Rectangle & Ellipse) is now implemented and will be included in v0.9.1. I will document it when v0.9.1 is out, but maybe having some sort of visual cue when <kbd>Alt</kbd> is being held could be useful to avoid confusion.

For now there is no way to change the keyboard button shortcut but it is a planned feature (tracked in #309). Fortunately, there is no conflict with other shortcuts. While <kbd>Alt</kbd> is already being used in the shape tools to displace the shape's position, it only works *after* the mouse click, while picking colors gets activated if <kbd>Alt</kbd> is pressed *before* the mouse click. As for the Linux issue, I'm not sure if we can do something about it until we implement better shortcut customization as mentioned above. In my end (Pop!_OS with KDE Plasma), I didn't notice any issues with it.
