### ISSUE TITLE
Bug : Save do not remember where the loaded .pxo was saved.

### ISSUE THREAD

**Issue by kakoeimon** [Orama-Interactive/Pixelorama#126]
It is not realy a bug but a future not implemented...
Load a .pxo and press save, the program will open the default file dialog without name and dir.
Make the program to remember the location of the loaded file.
Do the same for Save as, cause usually save as is used for itterations or alterations that belong to the same category (dir).

**Comment by OverloadedOrama** [comment]
Did #158 implement this feature, or are you asking for something else?

**Comment by kakoeimon** [comment]
Looks ok.
