### ISSUE TITLE
Request: Animation Loop organization.

### ISSUE THREAD

**Issue by kakoeimon** [Orama-Interactive/Pixelorama#127]
It's common to keep all the frames inside a single file, this means that standing frames, walk frames etc are going to be in the same file.
The problem is that right now there is only a single button for setting all the frames to be played in loop mode or ping-pong.
So the solution is to be able to organize the animations.
A fine example of this can be seen in aseprite : https://www.aseprite.org/docs/loop/

**Comment by Erevoid** [comment]
Actually this is in our immediate plans for v0.7, along with a remake of the timeline, so this will probably be added

**Comment by OverloadedOrama** [comment]
Frame tags have been implemented in the master branch, and will be included in v0.7. You can group your frames with them. Each tag has its own name, color and a range of frames. They're also being saved in .pxo files. You also have the option to have the animation play locally on each tag, just like on the gif below.

![Frame tag loop](https://user-images.githubusercontent.com/35376950/79702077-b0c56880-82aa-11ea-8a0e-d0d1dc829580.gif)

Currently the tags are not affecting the project on export, but if this wanted behavior we could implement it. Should we close the issue, or do you think there might be stuff missing from the way frame tags have been implemented?

**Comment by OverloadedOrama** [comment]
As of #217, the users can better organize their exported files with the help of tags by putting each tag group of frames on their own directories. This behavior is toggle-able on export. So now that tags affect the export settings too, I think we can close the issue. Feel free to re-open it if you think that more need to be added!
