### ISSUE TITLE
Bug : Save now always remembers the last saved file.

### ISSUE THREAD

**Issue by kakoeimon** [Orama-Interactive/Pixelorama#128]
Save now always remembers the last saved file. This means that if you save a file and then open another one and try to save, the suggested filename and location will be the previously saved file.
Same thing with export and save as.

**Comment by luiq54** [comment]
@kakoeimon can you elaborate a bit more? How is it different from #126?

**Comment by kakoeimon** [comment]
This was a side effect after closing #126

**Comment by luiq54** [comment]
I think what you mean is whenever a new image is created, the SaveAs FileDialog's path should be resetted.

The current situation may actually be better for people who keep their files in a single directory. They wont have to navigate to the same directory again and again.

**Comment by OverloadedOrama** [comment]
Should we close this issue?
