### ISSUE TITLE
Feature: Fill with pattern

### ISSUE THREAD

**Issue by Erevoid** [Orama-Interactive/Pixelorama#130]
There could be another option for the paint bucket tool to -instead of filling with a specific color- fill with a pattern.  It would also be nice for the user to be able to add their own patterns somehow, maybe similarly to how custom brushes work.

**Comment by novhack** [comment]
I can see this fully utilised for dithering. There could also be an option to offset the fill pattern.

**Comment by Derpford** [comment]
There does not appear to be a way to use custom brushes? Maybe I'm missing something.

**Comment by Variable-ind** [comment]
For using pattern
You select a drawing/area,
Copy the selection,
This selection will now appear as a new pattern

**Comment by Variable-ind** [comment]
> There does not appear to be a way to use custom brushes? Maybe I'm missing something.

And to add a custom brush/pattern (for fill tool we call it pattern) drag and drop the brush image in pixelorama (just like how you open any normal image)
And from the import dialog set **Import as:** option to "new pattern"
