### ISSUE TITLE
Better file explorer

### ISSUE THREAD

**Issue by Erevoid** [Orama-Interactive/Pixelorama#131]
The current way to save and browse the files from the program is a bit slow. I would suggest a file explorer that has major folders on the left, organized as a tree. A good example of this is the windows file explorer and since a lot of people are familiar with it, I believe it would be easier for everybody if this was implemented

**Comment by OverloadedOrama** [comment]
It would be very useful if they improved Godot's FileDialog node for this. Nevertheless, we also need a way to open and save files in HTML5 and Android platforms, which may mean ditching the FileDialog node entirely, at least for these platforms.
