### ISSUE TITLE
Symmetry Guides

### ISSUE THREAD

**Issue by Erevoid** [Orama-Interactive/Pixelorama#133]
A neat idea would be to make a "special" kind of guide that acts like a symmetry guide. Whatever you draw **relatively to the guide, not the center of the canvas as it already is with the brush options** will be mirrored. Being able to move the symmetry guide around enables you to make mirrored pixels anywhere you want them. You could choose an already placed guide to act as a symmetry guide. Only one horizontal and one vertical guide are allowed at a time. Symmetry guides could be added to a sub menu, maybe the "View" menu.

**Comment by OverloadedOrama** [comment]
I was thinking that symmetry guides could be visible when the user selected mirroring. If they select horizontal mirroring, horizontal symmetry guide gets visible, and same goes for vertical.

Should we have different guides for the left and right tools (that would make 4 symmetry guides in total), or is too much? Also, what about selections? Currently, if you have a selection, the center of symmetry becomes the center of the **selection, and not the canvas' center.** Should the symmetry guides automatically move to the center of the selection, when the user makes one?

**Comment by Erevoid** [comment]
Oh, you mean whenever you choose the mirroring option the guides appear? And if they appeared as of right now they would be at the center of the canvas but you can also move them around with my idea? Well sure, but having different guides for different tools (since the eraser has its own guides too) would be too much. Also yeah, 4 guides would also be a lot in my opinion, guides should be the same for both of the left and the right tools. So instead, mirroring shouldn't be inside the tools' options, instead it should be in a neutral place, like a sub menu. Or maybe close to the l/r colors as a switchable button. Similarly, clipping mode could be a button close to the l/r colors since it will apply to all of the tools. Otherwise the sub menus would be fine. Or maybe both. As for the selection no, if the user has already set a symmetry guide, if it moves with a selection it will be spoiled.

**Comment by TheGoklayeh** [comment]
Yes, one vertical and one horizontal symmetry line for all tools should be enough.

**Comment by bjorn** [comment]
I just tried the symmetry mode on the early_access web version (being available on the web is a great feature, btw!). I was a bit surprised that the guide was off by one on my 64x64 testing image. What is the reason for the +1 after dividing by 2?

**Comment by OverloadedOrama** [comment]
Sorry about that, a miscalculation on my part. I fixed it in the latest commit, thanks for letting me know!

**Comment by TheBricktop** [comment]
I have similar issue 
![obraz](https://user-images.githubusercontent.com/3866030/184116652-cb2e9d1a-81b9-474a-aa2b-754171ee7557.png)
