### ISSUE TITLE
Include lv_LV latvian language

### ISSUE THREAD

**Issue by nezvers** [Orama-Interactive/Pixelorama#150]
I couldn't find an option to add a new language in Crowdin but I'd be glad to fill translations for the Latvian language.

**Comment by OverloadedOrama** [comment]
Hello. Sorry, I thought Crowdin allowed everyone to update the target languages. I'll do some research to see if I can give members permission to add languages. In the meantime, I have added Latvian! Thank you very much for offering to translate!

**Comment by nezvers** [comment]
@OverloadedOrama Latvian is filled. Although I need to see it in action to see if the context is right.

**Comment by OverloadedOrama** [comment]
Latvian is now available in the master branch, thanks! You have been credited as "nezvers", let me know if you'd like to use a different name! If you'd like to test it, you can clone the master branch and run Pixelorama with Godot 3.2, or wait some days for v0.6.2 to be released! :)

**Comment by nezvers** [comment]
If it's possible Agnis Aldiņš (NeZvers).
Thank you for so amazing application and way to learn about Godot use for drawing.

**Comment by OverloadedOrama** [comment]
Your name has been updated! Thank you very much for the translation and the kind words!! :)
