### ISSUE TITLE
Blurriness

### ISSUE THREAD

**Issue by GiorgiBeriashvili** [Orama-Interactive/Pixelorama#159]
# Description

The rendered elements of the application appear to be blurry.

This is most likely unrelated to this specific software, as I have been experiencing this issue with Godot and other, mostly older software.

The issue seems to be fixed when `allow Hidpi` setting is enabled in `Project Settings > Display > Window > Dpi` section. I am unaware of potential side-effects.

I built the project myself to see the difference (from the current latest master branch; commit https://github.com/Orama-Interactive/Pixelorama/commit/30ce04b7f38e5ebca644993a33ac4eb521d1c481), and here are the results:

## HiDPI disabled

![HiDPI disabled](https://user-images.githubusercontent.com/34209889/74611300-d6e85400-5113-11ea-81aa-7e36f607b348.png)

## HiDPI enabled

![HiDPI enabled](https://user-images.githubusercontent.com/34209889/74611303-dea7f880-5113-11ea-9b56-e5a4ac95721a.png)

**Comment by OverloadedOrama** [comment]
On some HiDPI displays, the elements can be very small with HiDPI enabled. This is why it hasn't been enabled yet. In order to solve this, we also need to scale the UI up, which is problematic because of #140. I think it's best to keep HiDPI disabled until we solve #140, otherwise people with HiDPI monitors will have a hard time with everything being so small.

**Comment by OverloadedOrama** [comment]
Now that #140 has been resolved and we can scale the UI in the Preferences without issues, should "Allow hiDPI" be always enabled, or exposed as a setting to the user?

**Comment by zhengying** [comment]
Almost all macOS user use retina screen, But Pixelorama in retina screen is looking blur
I build the latest master source in my mac,  I enabled "Allow hiDPI", and set scale factor 2.2 ,
but the the font, and icons are still blur, the icons blur may be  icons are not use hidpi version.

![pixeloramaBlur](https://user-images.githubusercontent.com/1042545/109618174-332ce300-7b72-11eb-97fb-8b5cb513a34e.png)

**Comment by OverloadedOrama** [comment]
@zhengying Are the fonts and icons blurred if you set the scale factor to 2? It may be blurry because scaling by a non-integer factor, such as 2.2, is not pixel-perfect scaling.

**Comment by zhengying** [comment]
No, I tried factor  2, no improvement.

**Comment by iulover99** [comment]
I'm encounter the same blurry problem in my window 10 machine when I use the app in the download link provide at the page, are there new fix for this :(

**Comment by floppyhammer** [comment]
Still experiencing this on Windows with a 2K monitor. Any progress?

**Comment by Variable-ind** [comment]
Hy 👋, Does increasing the scale from preferences help?

**Comment by floppyhammer** [comment]
@Variable-ind Unfortunately no. However, along with allowing hidpi, it works perfectly on Windows.

**Comment by OverloadedOrama** [comment]
I wasn't able to make progress with this issue because I don't have a hiDPI monitor to test it myself. But since there's confirmation that it works perfectly with hiDPI enabled and now users can scale the UI up, I went ahead and enabled hiDPI in the project settings. It should be safe to close the issue now, but if you still encounter issues, feel free to report them!

**Comment by jsomedon** [comment]
Where is the option for turning on hiDpi support? I couldn't find it anywhere in preference.

**Comment by OverloadedOrama** [comment]
@jsomedon hiDPI is enabled by default, currently there is no way to turn it off from Pixelorama's Preferences.

**Comment by jsomedon** [comment]
> @jsomedon hiDPI is enabled by default, currently there is no way to turn it off from Pixelorama's Preferences.

So on my macbook pro(m1), Pixelorama's interface is pretty blur. If hiDpi is enabled by default, is there any other config option I need to set? I set scale to like x2 and while that makes stuff less blur, it makes things larger.
