### ISSUE TITLE
Export cannot resize the image.

### ISSUE THREAD

**Issue by kakoeimon** [Orama-Interactive/Pixelorama#161]
This is a master introduced bug it was working as expected in 6.1
Now we get this error in the console

ERROR: Cannot resize image when it is locked.
   At: core/image.cpp:886

 and it exports unresized image.

**Comment by OverloadedOrama** [comment]
From what I understand, Image.resize() needs the image to be unlocked to work in Godot 3.2 and I did not know that. Thanks for reporting the issue!
