### ISSUE TITLE
does crash on move selection twicely

### ISSUE THREAD

**Issue by Ogimle** [Orama-Interactive/Pixelorama#162]
1 new project
2 draw smth
3 add new frame and draw smth
4 onion skin on  +1 prev frame
5 rotate second frame
6 select area
7 move selection 
8 move selection
crash

v0.6.2, ubuntu 18.04, intel hd 620

**Comment by OverloadedOrama** [comment]
Most likely related to #161. I can replicate this issue just by making a selection and moving it with Shift.  Will commit a fix soon, thanks for reporting!
