### ISSUE TITLE
Can't undo or redo changes after changing onion frame settings

### ISSUE THREAD

**Issue by Wolfenrahd** [Orama-Interactive/Pixelorama#167]
After changing the values for "Past Frames" and "Future Frames", their ui elements seemed to keep focus, and I was unable to use the ctrl-z or ctrl-y shortcut in the main window.

**Comment by OverloadedOrama** [comment]
It happens with other spinboxes like brush size and FPS. I think it's default Godot UI behavior and I'm not sure if it can by changed by any setting. If it can't, I'll find a way to solve this manually.
