### ISSUE TITLE
Feature: Index color mode, (pallette changes can impact colors already painted)

### ISSUE THREAD

**Issue by ikeofkc** [Orama-Interactive/Pixelorama#171]
Feature request for canvas pallette adjustments so if you're working on something and you want to make different versions of it with different pallettes.

In the program aseprite it's implemented as an index color mode, but it could be implemented other ways possibly. See https://www.aseprite.org/docs/color-mode/?fbclid=IwAR3gex0l5wqaEh7QOEz-czv3681B7k6TRGDIsVRAWFMz7lsMvK9Y196zgIU#indexed

**Comment by novhack** [comment]
I would personally try to avoid locking user with a certain color mode when he's first creating a new image project - like _Aseprite_ or _Graphics Gale_ does.

My take on this would be to add three new features to the current palette panel:
- Add a button to palette panel which **enables/disables color indexing**. If user enables it then everytime a color is changed in the palette the same color in the canvas would be changed accordingly - currently this might be slow with the current replace color algorithm, but once it's accelerated with C++ it could work fine.
 - Add button to **append all colors that are in the canvas** but not in the palette to the current palette. This would allow users that didn't enable indexing to quickly switch from a `normal` mode to the `indexing` mode.
- Add a button/feature to **merge palette colors** when indexing is enabled - one common part for a lot of pixel artists workflows is when they reduce a number of colors in the picture and merge similar looking colors into one.

**Comment by ikeahloe** [comment]
I definitely agree that opt-in/enabling/disabling is the way to go. When i mentioned this in one of the reddit posts that was also my sentiment.

I'm coincidentally starting to learn Godot and GDscript for game creation reasons. I haven't done much coding outside of some python in blender, and appscript in google sheet.  Already it's feeling very fun and easy to learn, so if this isn't implemented in a few months I may fork and study the code to see if I can try my hand.
