### ISSUE TITLE
Request: Custom Shortcut Key on Tools

### ISSUE THREAD

**Issue by krisnaxda** [Orama-Interactive/Pixelorama#175]
i think shortcut key for pencil(O), and color picker(P) is too far and not efficient for left arm, it would be good if shortcut key can be changed. also how do i contribute to pixelorama for translation?

**Comment by novhack** [comment]
You can contribute to translations here: https://crowdin.com/project/pixelorama

**Comment by OverloadedOrama** [comment]
In a future version a way to re-map shortcut keys will be added... Maybe in v0.8, but I'm not sure yet.
