### ISSUE TITLE
Feature: Improved New Canvas Dialog box

### ISSUE THREAD

**Issue by luiq54** [Orama-Interactive/Pixelorama#178]
![image](https://user-images.githubusercontent.com/51489635/78023666-ae8b8080-7374-11ea-9c7d-051dd7f6da2a.png)
Features -
1) Lock canvas aspect ratio button 
2) Some default templates like 16x16, 32x32, 64x64, 128x128
3) It should remember the last created canvas size.

**Comment by OverloadedOrama** [comment]
I'm adding the up for discussion label for the 3rd feature. The new image dialog gets the size from the default size, which can be changed in Preferences > Image. Do we want that, or do we want it to remember the last created canvas size?

I was thinking that, when the program first starts, it could get the size from the default size, and if the user changes size again, it could remember the last created size.

**Comment by Calinou** [comment]
It seems GIMP remembers the last created size, so Pixelorama could do that as well for consistency.

**Comment by luiq54** [comment]
Maybe let it remember the last created size only during the runtime of the app. On next launch it reverts back to the defaults.
