### ISSUE TITLE
Move or condense infrequently used interface elements

### ISSUE THREAD

**Issue by lmerriam** [Orama-Interactive/Pixelorama#180]
There are a lot of things we can do to improve the Pixelorama UI, but by far the most impactful place to start is to condense or remove some of the tool options that are not used often enough to warrant having them constantly available at the top level of the program (and thereby adding complexity to the interface).

![Annotation 2020-04-02 114914](https://user-images.githubusercontent.com/1657444/78290079-068ec800-74d8-11ea-945f-59dafbfacce3.png)

- The pixel indicators and tool icons on the left hand side are a top candidate for condensing/moving, I love having the option but this is pretty much a set-once-and-forget thing, more suited to a secondary dropdown menu or even an option in a program-wide "view" settings menu. Even if some people like to use certain options for certain tools, that would be better solved with tool presets so users don't have to modify multiple settings every time they change to a certain tool.

- Onion skinning settings could be more suited a dropdown/popover, I find that I often change these settings across projects, but not while working within a single project.

- Palette options could be under a submenu, or even better could be done via direct manipulation (remove and add colors from within palette itself, like many other design tools). For me, palette options tend to get heavy use at specific times (when I am creating or modding a palette) but there is a long time in between using them, which makes them a good candidate for not being a top-level UI item.

Keeping an interface from becoming overcrowded can be hard in an open source project where everyone wants to add their favorite feature, but good UI is especially important for a design tool like Pixelorama so it should be a priority. Heuristics and guidelines could be put in place to help maintain consistency and usability as the project grows. Interested to hear what others think.

**Comment by Erevoid** [comment]
Heyo! For the new 0.7 update I've redesigned the UI so most of the things you mentioned are already fixed! The indicators and icons can be switched on/off under "Preferences", onion skinning got its own expandable button, frames and layers merged together and space is distrubuted better than the previous version! (As seen in this picture)

![Capture](https://user-images.githubusercontent.com/58960464/78295353-ae39e380-7534-11ea-8b0d-90353d0d9e22.PNG)

As for the palettes, being able to add and change colours easier is indeed necessary, so we'll try our best to fix the palettes' UI as well. Thanks for your feedback!

**Comment by Erevoid** [comment]
@lmerriam Thank you! Of course any kind of help is valuable so feel free to be opening new issues regarding the UI and how it could be improved! You can also join our discord server and discuss with us about it in its channel!

**Comment by OverloadedOrama** [comment]
Since the UI has changed a lot since the time of this issue's creation, I'll go ahead and close it. If you have any more feedback, feel free to open a new one (or re-open this, whatever you prefer!)
