### ISSUE TITLE
Palette tool options.

### ISSUE THREAD

**Issue by TheGoklayeh** [Orama-Interactive/Pixelorama#187]
Bunch of nice QoL things:

- Drag'n drop to rearrange colors in the palette.
- Auto sorting.
- Select two colors and make gradient between them.
- "Create palette from current sprite" would be amazing.

**Comment by novhack** [comment]
What exactly should the third option do? Hue shift between the two colours?

**Comment by TheGoklayeh** [comment]
Yes, something like this: https://youtu.be/BVBiUnBUB8c?t=449

**Comment by OverloadedOrama** [comment]
Drag and drop to re-arrange colors is already possible from the edit palette menu (which will go away soon) and "create palette from current sprite" has been implemented in v0.8 (and enhanced in v0.8.1). The rest of the features will be worked on for v0.9, but I'll close this issue in favor of #356.
