### ISSUE TITLE
Editing all colors in a selection.

### ISSUE THREAD

**Issue by TheGoklayeh** [Orama-Interactive/Pixelorama#188]
Modifying all the colors of a selection would be amazing
As seen in these two example, it is quite the poweful tool:
https://youtu.be/wiQJqddh4f8?t=761  
https://youtu.be/wiQJqddh4f8?t=1525

**Comment by OverloadedOrama** [comment]
This is added in #199, so I'll go ahead and close this issue. Feel free to re-open it if you had something else in mind.
