### ISSUE TITLE
Lighten/Darken Tool configurable shift.

### ISSUE THREAD

**Issue by TheGoklayeh** [Orama-Interactive/Pixelorama#189]
The lighten/darken tool is very nice. 
It would be even better with configurable/customable saturation, brightness and hue shifting to get nicer results than just lighter/darker: https://www.youtube.com/watch?v=PNtMAxYaGyg 
[Aseprite shading ink](https://www.aseprite.org/docs/shading/) is quite interesting too.

**Comment by OverloadedOrama** [comment]
I'm currently working on a "hue shifting" mode in the lighten/darken tool that will let the user configure the hue, saturation and value separately. The old way of shading will still be kept as a mode, for those who may prefer it.
![image](https://user-images.githubusercontent.com/35376950/97488957-2d9d6300-191c-11eb-942f-c996592e9e8a.png)
