### ISSUE TITLE
Pixel Perfect Pencil

### ISSUE THREAD

**Issue by novhack** [Orama-Interactive/Pixelorama#192]
Every major pixel art tool has this feature to enable fast drawing without doubles.
https://rickyhan.com/jekyll/update/2018/11/22/pixel-art-algorithm-pixel-perfect.html

**Comment by Calinou** [comment]
Good catch. It seems this can be done just after the Bresenham line algorithm?

**Comment by OverloadedOrama** [comment]
#222 implemented this, so I'll close the issue. Feel free to re-open it you think that something is missing/needs to change!
