### ISSUE TITLE
Line constrain in xy ratio

### ISSUE THREAD

**Issue by Kinwailo** [Orama-Interactive/Pixelorama#201]
Draw straight lines with constrain in 2:1, 1:1, 1:2 etc

**Comment by novhack** [comment]
Could you please describe this feature request in a little more detail?
It's already possible to draw a straight line constrained to a certain angle by holding `Shift + Ctrl`.

**Comment by Kinwailo** [comment]
A straight line constrained to 15 degree is draw as 4-4-3-4-4-3...
But in pixel art, we usually want a line draw as 2-2-2-2 or 3-3-3-3.

**Comment by novhack** [comment]
Oh I think I get it now. You mean lines like these, right?
![lines](https://user-images.githubusercontent.com/42614907/79320518-3d1e0700-7f0a-11ea-90b3-1cb07f2e21f7.png)

**Comment by Kinwailo** [comment]
Exactly.

**Comment by OverloadedOrama** [comment]
If we added an option in the Preferences to let the user change the the degree increment value, will it solve this issue?

**Comment by novhack** [comment]
2:1 is 26 degrees, 1:1 is 45 degrees and 1:2 is 74 degrees. Letting user chose an increment would not solve the issue. It would be better to have just two options:
- 15 degree mode 
- 2:1, 1:1, 1:2 mode

For comparison Aseprite and Pyxel Edit only constrain lines in 2:1, 1:1, 1:2 so I would rather default to it to not confuse new users.

**Comment by OverloadedOrama** [comment]
Would something like this work?

![image](https://user-images.githubusercontent.com/35376950/79355453-5775d600-7f46-11ea-9d66-58b30e1b0bdc.png)

**Comment by OverloadedOrama** [comment]
This is resolved in #281 right? Should we close the issue then?
