### ISSUE TITLE
Grid and guides should not be displayed in previews

### ISSUE THREAD

**Issue by novhack** [Orama-Interactive/Pixelorama#205]
Both previews are currently showing grid and guides but those should be visible only on the main canvas.
![Screenshot_20200415_214459](https://user-images.githubusercontent.com/42614907/79381543-6ec2bc80-7f62-11ea-8632-6c763f206f23.png)

**Comment by OverloadedOrama** [comment]
This happens because the world_2d of these viewports is set to be the same as the world_2d of the main viewport. This means that they're showing the exact same things as the main viewport. This should be easy to change, I'll work on it for a future update.

**Comment by OverloadedOrama** [comment]
Fixed in e6aea97f1b41d74d18e4c514966aab3b1c3bc5ea.
