### ISSUE TITLE
Include a background to all canvas previews

### ISSUE THREAD

**Issue by novhack** [Orama-Interactive/Pixelorama#206]
Currently previews in the export dialog and in the timeline frames have all transparent backgrounds so the drawings are with some themes hard to see.
I propose to add a checker board background to all previews mentioned (or more solid color for timeline frame previews).
![Screenshot_20200417_005000](https://user-images.githubusercontent.com/42614907/79514070-9a6aa300-8045-11ea-8fda-102b0a48eb60.png)
It should be considered if it's actually necessary to show a preview in the frame button since it mostly becomes unrecognizable (maybe a simple glyph that signifies that there is something in the layer would be better and more visible).
![Screenshot_20200417_004949](https://user-images.githubusercontent.com/42614907/79514073-9dfe2a00-8045-11ea-9cd2-b79585163eee.png)

**Comment by luiq54** [comment]
We can use the shader from #210 for the background.

**Comment by matthewpaul-us** [comment]
I was poking around the code for this, and I see that flip image already has a transparent checker background. I tried replicating the setup on the desaturate as a test, but it seems that the desaturation action causes the transparent checker to be affected by the desaturation as well. This might not be too bad for desaturation, but some of the other dialogues it could be wierd.
![image](https://user-images.githubusercontent.com/1484070/91191896-52c6e880-e6c3-11ea-94ac-f409089b850b.png)

**Comment by matthewpaul-us** [comment]
Also, looking at the project, it seems like this could be tied in pretty tightly with the [project card](https://github.com/Orama-Interactive/Pixelorama/projects/3#card-36206915) related to effect previews.

Is this something I should hold off on for the effects? I can do the animation cels and the export dialog only and leave the effect previews for @OverloadedOrama.

**Comment by OverloadedOrama** [comment]
I'm not sure why the desaturation effect affects the checker too. I'm going to replicate it too soon, I'll see if there's something wrong. Right now I'm working on creating an ImageEffect parent class from which most image effects will inherit. This'll make editing stuff that are common for image effects much easier. Then, I'll add checker backgrounds for the rest of the effects.

Feel free to do the animation cels and the export dialog if you want @matthewpaul-us!

**Comment by OverloadedOrama** [comment]
I managed to put a checker background to the rest of the image effects (except rotation) in f121c39ddc140fc6c95ba4b2556540eabaa95f37 and it seems to be working fine. The filters do not affect the background from what I see, including the desaturation effect.

**Comment by luiq54** [comment]
@OverloadedOrama The solution you mentioned in my PR is the most modular one in my opinion and I think that is how it should be implemented. It also won't affect the image that way.

**Comment by OverloadedOrama** [comment]
> @OverloadedOrama The solution you mentioned in my PR is the most modular one in my opinion and I think that is how it should be implemented. It also won't affect the image that way.

Indeed, that is what I ended up doing.

**Comment by matthewpaul-us** [comment]
That's odd, as I think I did what was in the PR (checker as a child of preview, with show behind parent set). After the code gets merged, I'll take a look and see what I didn't do correctly. Has that code been merged yet?

I think adding a parent class for the image effect would be great!
![image](https://user-images.githubusercontent.com/1484070/91211641-1c966280-e6dd-11ea-98f0-53498fc28ada.png)

**Comment by OverloadedOrama** [comment]
Yeah the code has been merged in the latest commit in `master`.
