### ISSUE TITLE
The checker board of transparent background.

### ISSUE THREAD

**Issue by Kinwailo** [Orama-Interactive/Pixelorama#208]
The checker now is 1 x 1 and scale with the zoom value, it is easy jittering. In other drawing app, they usually draw the checker bigger (10 x 10) and at a fixed size no matter what the zoom value.

**Comment by OverloadedOrama** [comment]
I'm surprised it took this long for someone to report this, to be honest. I was thinking about this issue for a long time, but I'm not sure how to actually make it work.

We need a way to keep the texture of the image remain the same, unaffected by the zoom value, but the image borders being affected, so they start and end where the canvas drawing space starts and ends. Like GIMP handles it. I'm really not a fan of how Aseprite handles it.

If anyone has any ideas of how this can be implemented, please let me know.

**Comment by Kinwailo** [comment]
Can use shader?

![image](https://user-images.githubusercontent.com/28286958/79594266-4d530380-810f-11ea-8a59-4b91a6fc803a.png)

**Comment by OverloadedOrama** [comment]
Have you managed to achieve the effect with shaders? If so, would it be possible for you to open a PR to implement this? I'm not very familiar with how shaders work yet.

**Comment by OverloadedOrama** [comment]
Implemented in #210.
