### ISSUE TITLE
Zoom as tool is weird

### ISSUE THREAD

**Issue by Kinwailo** [Orama-Interactive/Pixelorama#211]
Why not change the zoom label to a drop down with some predefined value, and add 3 button beside (zoom in, out, 1:1)

![image](https://user-images.githubusercontent.com/28286958/79639261-47b3f700-81bd-11ea-96ca-5ec615d54332.png)

**Comment by OverloadedOrama** [comment]
#523 made the label editable when double clicking it, fit to frame and 100% zoom are already buttons found in the zoom tool's options, and the zoom tool itself has been improved (#540), so I'll go ahead and close the issue now. The zoom tool itself will remain as a tool, at least until we implement an alternative such as the one discussed in #540, unless we decide to keep both.
