### ISSUE TITLE
Play animation buttons bug

### ISSUE THREAD

**Issue by jegor377** [Orama-Interactive/Pixelorama#219]
There is a bug in play animation buttons in AnimationTimeline script that is triggered when you for example start animation to play forward and then without stopping start to play backwards. When you do it, then both buttons will have "play animation" texture.
This happens because both buttons are set to be toggled. When you toggle one button then "play_animation" method is called and in there script changes opposing button's pressed value to be false. This triggers "toggled" signal and the whole cycle repeats (this might be dangerous because it's calling "play_animation" again and again). I tried to fix it and don't change type of the buttons but I failed.
```
func play_animation(play : bool, forward_dir : bool) -> void: # this is called on every toggled signal
	if forward_dir:
		Global.play_backwards.pressed = false # this triggers "toggled" signal
	else:
		Global.play_forward.pressed = false  # this triggers "toggled" signal
```
Also I want to keep you in mind that when you press play forward and then backward animation plays correctly but only buttons look like they are not playing anything.

**Comment by IagoAndrade** [comment]
Also, if you play one, and then play the other without pausing, and then click the second one again, instead of pausing it will keep playing and change to the "click to pause" texture. if you click one more time, it will finally pause.
