### ISSUE TITLE
Mirror View Horizontally

### ISSUE THREAD

**Issue by Wishdream** [Orama-Interactive/Pixelorama#227]
I think it's important for the artist to be able to mirror the entire view non-destructively.

It allows to quickly swap between a mirrored view and a non-mirrored view to check if their perspective is correct and non-slanted. Since it's not written to canvas, the process should not be slow. It also let's the artist export not flipped.

![krita-2020-05-06_05 23 29](https://user-images.githubusercontent.com/4660711/81118040-bb465a00-8f5a-11ea-9974-7298b85d9dc0.gif)

**Comment by Erevoid** [comment]
That can already be done! Shift H and Shift V to flip the image horizontally and vertically accordingly. You can also access it from the top menus under image>Flip Horizontal/Flip Vertical

**Comment by Wishdream** [comment]
No no no. The keyword is **non-destructively**. That means it does not apply to the image/canvas but the view instead. So it affects the entire view, so all layers are affected and when saving, it shouldn't be flipped.
