### ISSUE TITLE
Unable to start program from godot

### ISSUE THREAD

**Issue by CryptoKR** [Orama-Interactive/Pixelorama#245]
After cloning, and applying git submodule update --init, I am unable to start the program in godot (F5). 

I get "Attempted to call function 'new' in base 'NativeScript' on a null instance" error from var gif_exporter_native = preload("res://addons/godot-gifexporter/src/GifExporter.gdns").new(). From GifExporter.gd. 

The program doesn't run and closes immediately. What must I do?

**Comment by jegor377** [comment]
1. What OS are you using.
2. I have encountered the same problem and the issue was that I had to compile gif-exporter myself.

**Comment by CryptoKR** [comment]
I'm using linux mint 19.3. 
So I must compile the binary and copy and paste it into the directory? I'll try it out, thx

**Comment by jegor377** [comment]
Yea, when I've had this issue, I did all stuff that is necessary to compile gif-exporter and then in Godot I changed paths for libs to point to the new compiled ones. This fixed it for me.

**Comment by Schweini07** [comment]
@CryptoKR Did you fix it?

**Comment by OverloadedOrama** [comment]
Closing this as the GDNative gif exporter plugin has been replaced with a GDScript one in #295.
