### ISSUE TITLE
Guides global among all frames

### ISSUE THREAD

**Issue by jegor377** [Orama-Interactive/Pixelorama#246]
Wouldn't it be great if we could check some checkbox in settings to make guides to be shown the same in every frame? For example: I create guide in frame 1 and then I switch to frame 2 and there is the same guide.

**Comment by OverloadedOrama** [comment]
As a side effect of 54b628f6cba99126fa79b59de83531700028f33d, the guides are now the same across all frames. I'm not sure if having frame-specific guides is useful in any case, and I think it was a mistake of mine to make them frame-unique. So I'll go ahead and close this issue now. If you think that a settings option can be useful to turn this on and off, feel free to reopen the issue!
