### ISSUE TITLE
Flatpak: No brushes or patterns

### ISSUE THREAD

**Issue by NoeelMoeskops** [Orama-Interactive/Pixelorama#248]
Hi,

The "Patterns" menu shows up empty and the brushes only have three variants. Also, I needed to import all the pallets myself. Is this normal, Is there anyway of importing them manually?
(Fedora 32 using Flatpak)
![patterns](https://user-images.githubusercontent.com/10706939/82800261-b13dba00-9e7b-11ea-9f27-2367d5152a51.png)
![brushes](https://user-images.githubusercontent.com/10706939/82800299-c31f5d00-9e7b-11ea-8e8c-3af0028ce204.png)

**Comment by Schweini07** [comment]
The flatpak doesn't have the resources, I can confirm.
But I think it is maintained by @Calinou?

**Comment by Calinou** [comment]
The Flatpak has trouble finding its folders, but I don't know why exactly.

**Comment by OverloadedOrama** [comment]
I've looked into this, it appears that the Flatpak is copying the Brushes, Palettes and Patterns folders and pasting them into the app's root directory, while it should be placing them inside the "pixelorama" folder, which is supposed to be in the app's root directory. The app is looking for a "pixelorama" folder which has the Brushes, Palettes & Patterns folders inside it, but it cannot find it, hence why this issue occurs.

I've been experimenting with a solution on this PR https://github.com/flathub/com.orama_interactive.Pixelorama/pull/4, but all of my attempts seem to have been causing failed builds. Any ideas?

**Comment by Calinou** [comment]
> EDIT: It's possible that this occurs because there is already a file called "pixelorama" in the root directory, and according to this, you can't have a file and a folder have the exact same name in the same directory on Linux machines.

Indeed. We could rename the binary to something else, but I guess it would be better to rename that folder to something like `data` so it doesn't conflict.

**Comment by OverloadedOrama** [comment]
Yeah renaming the folder would be a better idea. This'll probably happen in the next stable version.
The folder got its name from #197. @sapient-cogbag would it be a problem if we renamed the folder "pixelorama" into something else?

**Comment by sapient-cogbag** [comment]
You'd definitely want to keep the name specific to the application since it is used for non-flatpak packaging styles (e.g. ~/.local/usr/share/<name> iirc), but if i was sensible it should just be in one path-generator function or variable nya.

**Comment by sapient-cogbag** [comment]
It should just be in XDGDataPaths.gd, `const config_subdir_name`

**Comment by sapient-cogbag** [comment]
HOWEVER

a better approach would be to run the application with XDG_DATA_DIRS set, to change the search path for data (e.g. to /data, such that the application will look for things in /data/pixelorama)

**Comment by OverloadedOrama** [comment]
Wouldn't it be better if we renamed the `config_subdir_name` into something like "pixelorama_data"? That way is it still application-specific, and it will solve the Flatpak issue.

**Comment by sapient-cogbag** [comment]
you could do that, but then you mess with the convention that the XDG locations use the app names.

The XDG standard is commonly used by applications, so i would think there's a good way to do it with flatpak? nyaa

**Comment by sapient-cogbag** [comment]
In fact i would hazard a guess that you can throw stuff in /app/share/pixelorama if flatpak changes XDG_DATA_DIRS nyaa (just looking at the yaml file)

**Comment by OverloadedOrama** [comment]
As a workaround to this and #321, I renamed the "pixelorama" folder to "pixelorama_data" for Windows, Mac and the Linux zip build, but kept "pixelorama" for the XDG locations. So Linux builds, including the Flatpak, will have the "pixelorama_data" next to the binary with the default brushes/palettes/patterns, but new data will use the XDG directories, inside the "pixelorama" folder, so we still go with the XDG convention.

So the issue should be closed when v0.8 is out. A better solution for the Flatpak might be to directly put the data to XDG_DATA_HOME/pixelorama, which I don't know if it's possible?

**Comment by Calinou** [comment]
> A better solution for the Flatpak might be to directly put the data to XDG_DATA_HOME/pixelorama, which I don't know if it's possible?

Built-in program data shouldn't be moved to an user data folder, as that folder should only include data generated by the user somehow (configuration files, *custom* brushes, …).

**Comment by OverloadedOrama** [comment]
That makes sense. So is this solution good enough?

**Comment by Calinou** [comment]
@OverloadedOrama That solution sounds fine to me :slightly_smiling_face:

**Comment by ssokolow** [comment]
> and[ according to this](https://stackoverflow.com/questions/14496897/mkdir-p-fails-when-directory-exists), you can't have a file and a folder have the exact same name in the same directory on Linux machines.

It's because UNIX filesystems take that "everything [that existed prior to the invention of networking] is a file" philosophy seriously.

What we see as files, directories, symlinks, device nodes, named pipes, etc. [are all seen as just different kinds of files](https://en.wikipedia.org/wiki/Unix_file_types) by the low-level APIs and you can't have two files with the same name.

**Comment by Variable-ind** [comment]
This is the solution/workaround:
1. Download the repository from [Here](https://github.com/Orama-Interactive/Pixelorama). (Click "Code" (the green button) and "Download Zip")
2. Unzip it after its downloaded and copy all the folders inside **pixelorama_data** (Brushes, Palettes, Patterns)
3. Go to the directory `/home/(put Username here)/.var/app/com.orama_interactive.Pixelorama/data/pixelorama` and paste those folders (merge or replace them if you have to)
4. You can now delete the zip file and the unzipped folder (from step 2) 

## Video instructions

https://user-images.githubusercontent.com/77773850/155936477-87d640fb-2fd7-4e34-a9cd-e6a310388d58.mp4
