### ISSUE TITLE
Pixelorama Command Line Interface

### ISSUE THREAD

**Issue by OverloadedOrama** [Orama-Interactive/Pixelorama#254]
It would be useful to be able to use Pixelorama's functions directly from the command line, like this https://www.aseprite.org/docs/cli/. I imagine it would help a lot with automation.

It should be possible to do given that Godot has an `OS.get_cmdline_args()` method for running projects with command line arguments.

**Comment by matthewpaul-us** [comment]
I'm adding some notes, as I've been doing research on this in the hopes that someone would get enough to work.

Here is a discussion about parsing command line arguments in a game: https://www.reddit.com/r/godot/comments/bomjhc/is_there_any_way_to_pass_arguments_to_the_game/

Here is a version of Godot Server that we could use to run headless. I have no idea if godot has code to determine if we are running via server or a normal version of godot. https://godotengine.org/download/server

What I am not sure about is whether we can use the same pixelorama project and run it headless based on command-line arguments. I took a look around to see if I could find another godot project that has similar capabilities, but didn't find anything
