### ISSUE TITLE
0.7 crashes when opening on macOS

### ISSUE THREAD

**Issue by gingerbeardman** [Orama-Interactive/Pixelorama#261]
Unrelated to #240

1. run the app
2. see the menu briefly
3. crash

I am running macOS 10.14.6 Mojave

0.62 runs fine.

[Pixelorama_2020-06-13-134458_matt.crash.zip](https://github.com/Orama-Interactive/Pixelorama/files/4774596/Pixelorama_2020-06-13-134458_matt.crash.zip)

```
default	13:44:34.205329 +0100	Pixelorama	  saved enable noise cancellation setting is the same as the default (=1)
default	13:44:34.410214 +0100	Pixelorama	27366555: RECEIVED OUT-OF-SEQUENCE NOTIFICATION: 7262 vs 7275, 513, <private>
error	13:44:35.703334 +0100	Pixelorama	ERROR: init_library: Condition "lib_path.length() == 0" is true.
At: modules/gdnative/nativescript/nativescript.cpp:1483.
error	13:44:36.582762 +0100	Pixelorama	ERROR: load_image: Error opening file '-psn_0_42309719'.
At: core/io/image_loader.cpp:56.
error	13:44:36.583083 +0100	Pixelorama	ERROR: get_child: Index p_index = -1 is out of bounds (data.children.size() = 0).
At: scene/main/node.cpp:1296.
error	13:44:36.583128 +0100	Pixelorama	ERROR: get_child: Index p_index = -1 is out of bounds (data.children.size() = 0).
At: scene/main/node.cpp:1296.
default	13:44:36.608200 +0100	loginwindow	-[PersistentAppsSupport applicationQuit:] | for app:Pixelorama, _appTrackingState = 2
default	13:44:36.608247 +0100	loginwindow	-[PersistentAppsSupport applicationQuit:] | App: Pixelorama, quit, updating active tracking timer
```

**Comment by OverloadedOrama** [comment]
The crash seem to be related to the gif exporter. I opened a PR to the gif exporter's repository some hours ago (nice timing!) (https://github.com/novhack/godot-gifexporter/pull/2). It's possible that if it gets merged, it may fix the issue.

**Comment by gingerbeardman** [comment]
I'll keep watching, thanks!

**Comment by OverloadedOrama** [comment]
@gingerbeardman It's possible that the PR I mentioned above might have solved the issue. I don't have a Mac to test it, so would it be easy for you to go to [Pixelorama's Action tab](https://github.com/Orama-Interactive/Pixelorama/actions) and grab a Mac artifact to download and test it?

**Comment by gingerbeardman** [comment]
Indeed it has - that 0.8-dev opens just fine!
