### ISSUE TITLE
Allow colors to be selected via number row or other hotkeys

### ISSUE THREAD

**Issue by matthewpaul-us** [Orama-Interactive/Pixelorama#262]
While working in the editor, I'd like to be able to quickly switch colors on my tools. I was thinking that the first few colors could be hotkeyed to the number row so that I could hit 1 for the first color, 2 for the second, and so on. Right-tool selection would be done using the chord Alt+1, Alt+2, etc.

There is some overlap with #125, as adding some way to select another color in the image will also get rid of the need to move the mouse all the way to the palette and back for a color change.

**Comment by gingerbeardman** [comment]
I'm working in 1-bit (b&w) and this would be very useful for me.
