### ISSUE TITLE
Open or New error

### ISSUE THREAD

**Issue by wyattbiker** [Orama-Interactive/Pixelorama#265]
Mac OS X
Godot 3.2.1 stable

Just cloned the latest project version of PO. When I click on New or Open I get the following error. Any ideas how to fix?

Invalid call. Nonexistent function 'file_menu_id_pressed' in base 'Control (Main.gd)'.

Here is the code where it pauses:

![image](https://user-images.githubusercontent.com/930478/85408394-75f1e200-b532-11ea-8241-a58004505880.png)

**Comment by OverloadedOrama** [comment]
Sorry about that, I made some changes to the menus recently and forgot to change the splash screen. A fix will be committed immediatly
