### ISSUE TITLE
animation_type in ExportDialog does not seem to be set.

### ISSUE THREAD

**Issue by wyattbiker** [Orama-Interactive/Pixelorama#266]
Geia sou Manoli ti kaneis.

I click on the Export As and click Animate tab so I can create a GIF. I already modified the code to allow GIF as the export type in the dialog (It was disabled).

The `animated_type` variable is never set so it never goes to the export GIF code.
 It always remains 0 (AnimationType.MULTIPLE_FILES).  

When does that variable get changed? I assume at some point it should be set to AnimationType.ANIMATE

**Comment by OverloadedOrama** [comment]
I'm not sure what the issue is here. Judging from your previous issue and from the fact that the export type was disabled, you must be using macOS. Gif exporting currently only works on Windows and Linux.

**Comment by wyattbiker** [comment]
Yes I figured out what I was doing wrong.  I was neglecting to select from the drop down the All Frames as Single File Animation
