### ISSUE TITLE
Can each frame have a custom delay?

### ISSUE THREAD

**Issue by wyattbiker** [Orama-Interactive/Pixelorama#267]
Geia sou pali :)

I noticed PO uses FPS for the animation. Is there a way to change a custom delay per frame?
PO can export to GIF. Can it also import a GIF and show the frames?

Thanks

**Comment by OverloadedOrama** [comment]
Hello! Right now this isn't possible, but it's a good idea for a future feature. We could have frame properties, where the user can set a delay for each frame. This should overrwrite the FPS setting, both when previewing the animation inside Pixelorama, and when exporting as a gif.
