### ISSUE TITLE
Canvas Resizing

### ISSUE THREAD

**Issue by Burntninjas** [Orama-Interactive/Pixelorama#268]
Being able to drag and drop images into the editor would save time having to redraw things every time I want to use a larger image surface.

**Comment by OverloadedOrama** [comment]
Dragging and dropping files into Pixelorama while it's running to import them is already possible in the master branch and will be included in v0.8. I'm a little confused as to what you mean by "save time having to redraw things every time I want to use a larger image surface". Are you asking for something else?

**Comment by Burntninjas** [comment]
I was asking if adding canvas scaling would be added, for instance changing the canvas from 64x to 128x while the content inside stays the same.

**Comment by OverloadedOrama** [comment]
Canvas resizing has also been implemented in the master branch recently and will be included in v0.8!
![image](https://user-images.githubusercontent.com/35376950/85719772-69b78180-b6f8-11ea-9fe4-96a23f4297f8.png)

It will most likely look different in the final version, but it does work.

**Comment by sirsnowy7** [comment]
Shouldn't this issue be closed?
