### ISSUE TITLE
Feature: A palette

### ISSUE THREAD

**Issue by novhack** [Orama-Interactive/Pixelorama#27]
Is suggest adding a palette to one of the side panels. Currently Godot color picker has one but it's not really ideal for efficient drawing.

It should be possible to add new colors, edit existing colors, copy and move them on the palette. Palette could be stored in the .pxo with the image. Exporting and importing to image formats could be also a nice feature.

How it looks in Pyxel Edit but it is very similar in other editors too:
![palette](https://user-images.githubusercontent.com/42614907/69527435-9772f700-0f6c-11ea-8bc4-299eec39c04d.png)

**Comment by OverloadedOrama** [comment]
Noted as part of the custom color picker that will happen in the future! I'd like to point out however, that palettes already get stored in .pxo files!

**Comment by novhack** [comment]
Great. In my opinion it would be better if it was a part of the main gui. When drawing pixel art selecting colors is something that is done very often so having it as a part of a color picker dialog could really worsen workflow.

**Comment by OverloadedOrama** [comment]
> Great. In my opinion it would be better if it was a part of the main gui. When drawing pixel art selecting colors is something that is done very often so having it as a part of a color picker dialog could really worsen workflow.

Definitely agree there. The artists of my team have already expressed their desire on having the color selector-from-screen as a separate tool, rather than it being part of the color picker dialog.

**Comment by OverloadedOrama** [comment]
Hello again. Palettes now exist in Pixelorama, with the help of @greusser. They are stored as .json files in the "Palettes" folder, found in Pixelorama's root directory, just like the Brushes. You can create and edit palettes inside Pixelorama, too. Being stored as invididual .json files make them easily shareable as well. @greusser has also added GPL importing!

I'm also thinking of adding importing PNG files as palettes as well, and maybe a "create palette from sprite's color" button, but these will not happen in v0.6

You can try them now and see if you like them, or you can wait for v0.6 which is expected to release within the next few days! For now, I'll close this issue. Feel free to reply or open a new one if you have any more suggestions, or encounter issues. Thank you!
