### ISSUE TITLE
Scrollbars for image panning

### ISSUE THREAD

**Issue by wyattbiker** [Orama-Interactive/Pixelorama#271]
When canvas is larger than image viewport would be nice to allow scrollbars appear or provide some panning capability.

**Comment by OverloadedOrama** [comment]
Panning is already possible with the middle mouse button, the Space button, and with the arrow keys on your keyboard. Scrollbars would be nice to have too.

**Comment by wyattbiker** [comment]
The Space and Arrows keys work but need to pan faster. Also when panning, it tabs through various buttons in the Right panel.

As an FYI:
Mac doesn't have clickable middle button. It has Left click, Right click and touch slide ( acts like middle scroll wheel of mouse)  https://youtu.be/qn6fz_6_fcw?t=178

For example with ASE I can touch slide up/down/left/right and scrolls the viewport. Actually this happens for any application scroll bars appear including Pixelorama.
