### ISSUE TITLE
[macOS] Option to use system file selector

### ISSUE THREAD

**Issue by gingerbeardman** [Orama-Interactive/Pixelorama#274]
I find the built-in file selector very difficult to use, because it has few of the features and benefits that the system file selector has.

So, it would be nice to have the Option to use system file selector on macOS.

Thanks!

**Comment by Schweini07** [comment]
@OverloadedOrama This may be possible, see: https://godotengine.org/qa/4312/is-there-a-way-to-open-the-os-file-manager

**Comment by OverloadedOrama** [comment]
I tried using `OS.shell_open("file://")` but it just opens a window of the system file explorer, not the system file selector. AFAIK, I don't think `OS.shell_open()` can return a file path either. The PR linked in the answer also seem irrelevant to the issue. Is there some other way to do this, or am I doing something wrong?

**Comment by gingerbeardman** [comment]
That code just opens the directory in Finder (file manager) rather than opening a file selector/picker window.

I looked into it and apparently not possible/refused to be implemented by Godot

https://github.com/godotengine/godot/issues/13177

**Comment by gingerbeardman** [comment]
So my main issue is that when I open the file selector it is at the filesystem root.

I expect it to be at my home directory root.

**Comment by Schweini07** [comment]
Using `OS.shell_open(str("file://", "/"))` on my Linux machine.

My defaut file system manager (Dolphin) opens up.

**Comment by Schweini07** [comment]
Now also tested with Nautilus and `OS.shell_open(str("file://", "/home/"))`, also works.

**Comment by gingerbeardman** [comment]
@Schweini07 not sure I follow. the request is not for file manager to pop up

but for system file picker to be used instead of godot file picker. 

Anyway, see above, Godot will not allow this. 

Closing, I guess...

**Comment by Schweini07** [comment]
Yes, saw this right now, followed the conversation wrong ^^.

**Comment by gingerbeardman** [comment]
Some options:
- new https://github.com/bruvzg/mac_file_panels
- old https://github.com/GodotExplorer/NativeDialogs

**Comment by gingerbeardman** [comment]
Almost added to godot: https://github.com/godotengine/godot/pull/47499
