### ISSUE TITLE
[Web version] Cannot download or upload files

### ISSUE THREAD

**Issue by Xfiudong** [Orama-Interactive/Pixelorama#280]
On https://orama-interactive.github.io/Pixelorama/early_access/, it is not possible to download the project files or the png/gif created.
The files are only created on what looks like a virtual machine.

**Comment by OverloadedOrama** [comment]
The early access web page is meant to be used as an easy way to check out new features and play around with them. Currently, Pixelorama does not support the HTML5 properly, because of the issue you mentioned. Once this is resolved, the Web will be an officially supported platform.

**Comment by Xfiudong** [comment]
Thanks for your very quick answer! I just wanted to let you know as I shared the web interface to some friends and they all told me it was too bad they couldn't download their little tests. They found the app very easy to use and quite attractive though ;)

**Comment by OverloadedOrama** [comment]
I'll work on it! Unfortunately, it's a bit hard because Godot, the engine Pixelorama is made on, doesn't have direct support for accessing the file system in the HTML5 platform. But it is possible using JavaScript, and I managed to make .png files downloadable in the Web version! All that remains now is to make .pxo files downloadable too, and to be able to load image files, pxo files and palette files too. After that, Pixelorama should be fully functional in the Web!

**Comment by OverloadedOrama** [comment]
So far, saving .pxo and .png files is working, as well as loading image files and palette files. The only issue I'm encountering is loading .pxo files. In 0.8, pxo files are made out of a text part in JSON format, and a binary part for all the image data. I'm not sure yet how to handle loading these files in JavaScript.

It's also worth noting that, when Godot 3.2.3 comes out, users will be able to drag and drop files into the Web version of Pixelorama to open them. Perhaps this will solve the .pxo loading issue. (See https://github.com/godotengine/godot/pull/39604)

Now that most stuff are working, should this issue be closed?

**Comment by Xfiudong** [comment]
From my point of view, yes :) Thank you very much for your very quick bugfix!!!

There is a little difference with the standalone version though: you cannot export gif but I am being nitpicking!

**Comment by OverloadedOrama** [comment]
Yeah unfortunately gif exporting only works on Windows and Linux for now. It may be possible that one day the Web version will support gif exporting, perhaps once Godot allows GDNative on HTML5, but we'll have to wait and see. Closing this then! :)

**Comment by OverloadedOrama** [comment]
Update: The GDNative gif exporter addon has been replaced with a GDNative equivalent in #295, which works on all platforms, including the Web version!
