### ISSUE TITLE
Gif exporting crashes the app

### ISSUE THREAD

**Issue by randomdudelopk** [Orama-Interactive/Pixelorama#283]
when i finished making my gif i export _as_ and it closes the app and when i went to look at my files theres no gif

**Comment by OverloadedOrama** [comment]
That sounds like an issue with the gif exporter. Can you tell us what Operating System you're using, and the size of the image you're trying to export?

**Comment by OverloadedOrama** [comment]
Closing this as the GDNative gif exporter plugin has been replaced with a GDScript one in #295.
