### ISSUE TITLE
Del button in menu (export, save as...) deletes selection

### ISSUE THREAD

**Issue by Leyk973** [Orama-Interactive/Pixelorama#296]
**Pixelorama version:**

v0.7

**OS/device including version:**

Windows 10, french keyboard

**Issue description:**

Using the Del button on my keyboard (french azerty if that matters) to rename a file for export or save as, I deleted what was selected on my frame using the selection tool.

**Steps to reproduce:**
Open project, select a frame, select part of image using the selection tool.
Select export or save as (without deselecting what you selected) in the File menu, focus on a text zone, use the Del key in it.

The backspace key works as expected, though.

**Comment by OverloadedOrama** [comment]
I can replicate the issue in v0.7, but not in v0.8-dev. Pressing "Del" when focusing on a text zone deletes the text but does not affect the selection tool, so it looks like it has already been solved. If you want, feel free to download a build from the Actions tab, or test it on the [Early Access Web Version](https://orama-interactive.github.io/Pixelorama/early_access/).
