### ISSUE TITLE
Adding multiple file editing

### ISSUE THREAD

**Issue by 3mic4nia** [Orama-Interactive/Pixelorama#298]
Hello,
It could be useful to add multiple file editing through tabs

Tanks you.

**Comment by OverloadedOrama** [comment]
This has already been implemented in v0.8-dev. You can try it out with a build from the "Actions" tab, or with the[ Early Access Web Version](https://orama-interactive.github.io/Pixelorama/early_access/). It will be a part of v0.8 when it becomes stable.

![image](https://user-images.githubusercontent.com/35376950/89711242-a7fbbe00-d991-11ea-9383-c3091aba5761.png)
