### ISSUE TITLE
Image Effects preview not updating when changing "affect" area

### ISSUE THREAD

**Issue by luiq54** [Orama-Interactive/Pixelorama#302]
**Pixelorama version:**

0.8-dev

**OS/device including version:**

Applicable to all OSs

**Issue description:**

When changing the "affect" area (for example Current Cell to Current Frame ) in Image effects like Flip or Adjusting HSV, the preview doesn't reflect the changed affected area . 

**Steps to reproduce:**
Draw on 2 different Layers. Open Adjust HSV dialog and change affected area from Current Cel to Current Frame.

**Comment by luiq54** [comment]
I went through the code, we might need to add a `setget` function to all `affect` variables in each dialog script to update the preview.

**Comment by OverloadedOrama** [comment]
I don't know if `setget` is required, I think we'd just need some extra code in `update_preview()` that merges all of the layers together. I agree that this is nice to have, only thing that worries me is that merging images very often can have a bit of an impact in performance.

**Comment by OverloadedOrama** [comment]
Actually, now that I think about it, you are right. It would be better to use 'setget' and merge the layers only then, and when the dialog is about to be shown. My idea, merging the layers on `update_preview()` would make unnecessary merges, as we'd only need a merge when the option change, and when the dialog is about to be shown, if the affect option is set to something different than "current cel" .
