### ISSUE TITLE
White box which appears around selected color disappears as soon as  we start to paint. 

### ISSUE THREAD

**Issue by yuyutsupoudel** [Orama-Interactive/Pixelorama#308]
**Pixelorama version:*
0.7

**OS/device including version:**
linux

**Issue description:**
The white box which appears around selected color disappears as soon as i start to paint. there is no indication regarding which color is selected.

**Steps to reproduce:**
select a color.
start painting.

**Comment by OverloadedOrama** [comment]
Hello, I'm not entirely sure what the issue is. If I select a color and start painting, I don't notice anything disappearing. What do you mean by "white box"? Is it possible to provide a screenshot or a video showcasing the issue?

**Comment by yuyutsupoudel** [comment]
[Youtube video](https://youtu.be/JisLwqM0rLs)
If you notice, a white box appears around selected color but as soon as we start to paint, that disappears and i dont know which color i selected just by looking at color palette.

**Comment by OverloadedOrama** [comment]
Oh you were talking about selecting a color from a palette, I thought you were referring to the color picker buttons. I can replicate the issue, it's because they're losing focus. To fix it, we need to make the buttons have a pressed state when they're selected, and unpressed when something else is selected, like the cel buttons in the timeline work. Perhaps having a ButtonGroup for all palette buttons would make it easier. Will work on this when I have time, thanks for reporting!

**Comment by luiq54** [comment]
There is already a signal function called `on_color_select` (in `PalleteContainer.gd` )which is fired when one of the color buttons is pressed. Also the `index` of button is passed to the function. Maybe add a variable which tracks currently selected button and highlights it.

**Comment by matthewpaul-us** [comment]
Would this be covered by the two tool swatches above the palette and below the preview?

Would this change be only to reinforce which color is selected or is there some other functionality I've missed?

**Comment by OverloadedOrama** [comment]
The two color buttons already show the currently selected colors, but the issue is that, if the user selects a color from a palette, it's not visible which color has been selected in the palette itself.

**Comment by yuyutsupoudel** [comment]
I think it would be easy to implement since issue is that box disappears not that box does not appear. 
My main issue with this is that if you have color palette which has lots of colors, its quite hard to know which color from color palette is selected. Issue is not that big but just a minor inconvenience.
