### ISSUE TITLE
Problems with circle blended brush

### ISSUE THREAD

**Issue by azagaya** [Orama-Interactive/Pixelorama#32]
Hi!
I've noticed a blending issue regrading the circle blended brush. It is related to this godot issue: https://github.com/godotengine/godot/issues/31124 but is probably not going to be solved in godot.
The following image shows the issue:

![imagen](https://user-images.githubusercontent.com/46932830/69975364-d1f90880-1505-11ea-87f3-8d0e08241f2a.png)

At the right, you can see the result of using the brush as is now. Transparent edges become dark if they are blended over a transparent backgraound. I implemented a custom function in gdscript to use instead of `blend_rect`, and with it we can get the result at the left, which in my opinion is way better (although slower). I also tried fixing the issue in godot in a custom build, and gives similar result than the one of the left, but as i said, i think this won't be fixed in godot because of performance (someone explained it to me on irc).

So i think the possible solutions are:

- Using custom blending function in GDScript (I can PR the one i made)
- Using custom godot engine build with the fix (a hassle, but will perform better i think)
- Wait for it to be fixed in godot.

**Comment by OverloadedOrama** [comment]
Since it's an open-source project, I don't think it's a good idea to make a custom Godot build, since everyone'll be using the original build. And waiting for it to be fixed isn't a real solution either, so 2 and 3 are out. I think the first solution would be the best. A PR would be helpful!

I at least wish Godot would add another extra method that, although slower, produces better results, instead of replacing the current one, since they don't want to sacrifice performance.

**Comment by azagaya** [comment]
Ill make the pr late today. I can reach godot devs on irc and ask them if they would merge a PR with an extra method for this. If they agree ill also make a pr for that. Anyways, that change will take time to reach a stable build, so custom method in gdscript would still be neede in the meantime

**Comment by OverloadedOrama** [comment]
Thanks, I appreciate it!

**Comment by azagaya** [comment]
I made the PR. Also, i've noticed that the brush paints several times when you click in one place, making it less transparent than the selected color. Is this intended?

**Comment by OverloadedOrama** [comment]
I've noticed it too. It's not intended, but I'm not sure how to fix it. I've been focusing on the UI mostly these days and I haven't tried fixing it yet.

**Comment by OverloadedOrama** [comment]
Turns out the PR caused bugs when the user was drawing a custom brush near the edge of the canvas or the rectangle selection, if any. I fixed it in 8b913553aac3ca0e3a6a47b021230451d9715748

**Comment by azagaya** [comment]
Oops, i didn't take that into account... sorry
