### ISSUE TITLE
[macOS] Cannot create pixelorama directory

### ISSUE THREAD

**Issue by huskeee** [Orama-Interactive/Pixelorama#321]
**Pixelorama version:** 
22746c8

**OS/device including version:** 
macOS Mojave 10.14

**Issue description:** 

Pixelorama tries to create the pixelorama folder (brushes/palettes location) in ./Pixelorama.app/Contents/MacOS, in the same directory as the executable. This doesn't work because there can't be a folder and a file with the same name in the same location.

**Steps to reproduce:**
1. Run Pixelorama from a terminal (e.g. `./Pixelorama.app/Contents/MacOS/Pixelorama` )
2. Pixelorama tries to create directories in /Pixelorama.app/Contents/MacOS/ (it shows in the logs)
3. This fails because it tries to create a folder named "pixelorama" alongside the executable file named "Pixelorama"

**Comment by OverloadedOrama** [comment]
I renamed the "pixelorama" folder to "pixelorama_data" in 5932f838316f724e4e80d601a3bb5a75dc3cef29, can you test if it works now?

**Comment by OverloadedOrama** [comment]
Closed in #324.
