### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by MaGaRCaN** [Orama-Interactive/Pixelorama#330]
I've been using Pixelorama for a while. During this time I've found some missing features wold be interesting for enhance this awesome piece of software.

**Feature/enhancement description:**

1. Magic wand selection tool
2. Lasso selection tool
3. Be able to draw standar polygons such as rectangle or ellipse
4. Create color palette between two given colors

**Comment by Schweini07** [comment]
Should this be split into multiple issues?

Would probably be preferable for the roadmap.

**Comment by OverloadedOrama** [comment]
Thanks for the suggestions! To better organize the issues, I will close this specific one in favor of #129 (suggestion #1 and #2), #359 (suggestion #3) and #356 (suggestion #4).
