### ISSUE TITLE
PoolVectorArray locking issues

### ISSUE THREAD

**Issue by OverloadedOrama** [Orama-Interactive/Pixelorama#331]
**Pixelorama version:**
v0.8, but it happens with v0.7 too, probably less often. Not sure about previous versions.

**OS/device including version:**
Windows 10 64-bit. Most likely happens in all platforms.

**Issue description:**
When working with PoolVectorArrays, or classes that use them, like Image, Line2D, sometimes errors saying "resize: Can't resize PoolVector if locked" appear in the debug console. They look like this. 
![image](https://user-images.githubusercontent.com/35376950/93646903-dac4b780-fa0f-11ea-96de-fed4cd7a6211.png)

Depending on the situation, it can be relatively harmless, like some tiles missing when drawing the isometric grid, and others it can prevent something from working at all, like when exporting an image to png, an error with code 23 (ERR_LOCKED) appears. 

I have observed this issue happening sometimes when: (will update the list if I find more occurrences)
- ~~Drawing the isometric grid. Some of the tiles might be missing.~~ **EDIT: No longer relevant as the isometric grid system has changed.**
- ~~Exporting the project. `Image.save_png()` returns code 23 and the file fails to get saved. I've noticed that if I draw something and then attempt to export again, it usually works that time.~~ **EDIT: Most likely fixed in 63410bdb46c0d5cd3bc68c7448b360a2d5c8cbcf**
- Creating guides. Sometimes the newly created guide doesn't appear, but text showing its position in pixels does appear.
![image](https://user-images.githubusercontent.com/35376950/93647437-17dd7980-fa11-11ea-8220-b24a8e299d62.png)
- Sometimes symmetry guides also don't get created too when making/opening a project.
- The experimental shader feature. Sometimes when trying to apply a shader to the image, it showed the same error in the console and the cel became blank. This feature is hidden in v0.8, but you can find it in the code. To make it appear, just uncomment the Shader line from `setup_image_menu()` in TopMenuContainer.gd
- Using the **screen** color picker found in the ColorPicker node sometimes does not work and prints "resize: Can't resize PoolVector if locked" in the debug console.

**Steps to reproduce:**
Honestly, I'm not sure. This error seems very random, although I'm guessing it has to do with the way PoolVector handles memory. Just play around with the occurrences I mentioned above, open multiple projects, and you'll come across this error sooner or later.

This is most likely a Godot bug, but so far I haven't been able to reproduce it in a minimal project in order to submit it to Godot's issues. If anyone knows anything more about the nature of this issue, or potential workarounds/solutions, feel free to reply. It's also worth noting that PoolVector is going away in Godot 4.0, so it's possible that this issue will get fixed when 4.0 is released.

**Comment by OverloadedOrama** [comment]
> Exporting the project. `Image.save_png()` returns code 23 and the file fails to get saved. I've noticed that if I draw something and then attempt to export again, it usually works that time.

Since 63410bdb46c0d5cd3bc68c7448b360a2d5c8cbcf, I haven't been able to reproduce this issue, so it may be safe to assume that it is now fixed. It seems like the `processed_images` Array had to be cleared before creating a new Image. I'm still unsure what the exact nature behind this issue is.

**Comment by qarmin** [comment]
Such locking errors I have when working with different Image functions.
Looks that after executing some functions, memory get corrupted and shows this errors.

I believe that fixing https://github.com/godotengine/godot/issues/46480, https://github.com/godotengine/godot/issues/46481, https://github.com/godotengine/godot/issues/46483 etc. will fix this issues in Pixelorama.

I probably can't fix this issues due to not having enough skills, but I can provide easy to reproduce steps with minimal projects(just like in issues above)

**Comment by Variable-ind** [comment]
**Steps to reproduce:**
This error seems to happen when pixelorama is put under much load/stress (trying motion painting with a speed of 100 Fps always causes this bug). i tried it 3 times and it happened every time:
_Attempt 1:_

https://user-images.githubusercontent.com/77773850/125450955-6e039a43-c66e-4cc9-933a-fc0f030b7f75.mp4

_Attempt 2 and 3 (both one after another)_

https://user-images.githubusercontent.com/77773850/125451036-bf834e34-95e3-44c5-b841-d644313a134d.mp4

**Comment by Variable-ind** [comment]
A new error reproduction steps for PoolVector isues in Godot screen ColorPicker:

https://user-images.githubusercontent.com/77773850/126728750-6b9b4ecc-8dd3-44b3-a9f8-7ac68b8afe7f.mp4

**Comment by OverloadedOrama** [comment]
It's very likely that the latest commit (1d20295f7d846fad4f9da70801d46e5866d16b70) might have finally fixed the issue. Or at least it made it more rare. I haven't been able to reproduce the issue so far after these changes.

The changes in that commit are that images no longer remain [locked](https://docs.godotengine.org/en/stable/classes/class_image.html#class-image-method-lock) forever, and they get unlocked after the user is done with drawing. It seems that this was the cause of the issue. Maybe the fact that images were locked didn't let any other PoolVector also get locked? Some kind of memory conflict perhaps? In any case, it's very possible that this problem may have not been solved, or may re-appear again in the future. If that's the case, we'll re-open this issue. Nevertheless, Godot 4.x gets rid of PoolVectors and images will no longer require locking/unlocking to get edited, so if we move to Godot 4.x, this problem should never appear again.
