### ISSUE TITLE
update pixelorama snap to 0.8

### ISSUE THREAD

**Issue by pixelr0** [Orama-Interactive/Pixelorama#336]
snap version is 0.7.0  https://snapcraft.io/pixelorama

**Comment by Schweini07** [comment]
This is the repository for the snap https://github.com/Aury88/pixelorama, maintained by @Aury88.
You may want to open the issue there.

**Comment by pixelr0** [comment]
oh, right! thanks o/

**Comment by Schweini07** [comment]
Can be closed now, Snap has been updated.
