### ISSUE TITLE
Export as gif crashes

### ISSUE THREAD

**Issue by sprajagopal** [Orama-Interactive/Pixelorama#338]
**Pixelorama version:**

v0.7 Linux 64bit

**OS/device including version:**

**Issue description:**

I tried exporting as gif and Pixelorama crashed.

**Steps to reproduce:**
I had about 15 frames.
Export as animation (default options)
Pressed Ok. 
Crash

**Comment by OverloadedOrama** [comment]
This is a known issue with v0.7's gif exporter. I recommend download v0.8, which has a new gif exporter. I'm closing this issue for now as it's no longer relevant to the new version. Feel free to re-open it if you experience the same issue in v0.8.
