### ISSUE TITLE
Pixelorama fails to run sometimes - Can't load cached sub-resource

### ISSUE THREAD

**Issue by OverloadedOrama** [Orama-Interactive/Pixelorama#339]
**Pixelorama version:**
v0.8

**OS/device including version:**
Linux (reported on Solus OS)

**Issue description:**
I haven't encountered this issue personally, but two Linux users, one using a notebook with Solus OS, said that Pixelorama sometimes fails to run and shows this in the console.
```
Godot Engine v3.2.3.stable.official - https://godotengine.org/
OpenGL ES 2.0 Renderer: GeForce 930MX/PCIe/SSE2
OpenGL ES 2.0 Batching: ON
 
Detected system where we should use XDG basedir standard (currently Linux or BSD)
ERROR: poll: res://src/UI/BrushButton.tscn:18 - Parse Error: Can't load cached sub-resource: res://src/UI/BrushButton.tscn::3
   At: scene/resources/resource_format_text.cpp:528.
ERROR: load: Condition "err != OK" is true. Returned: RES()
   At: core/io/resource_loader.cpp:208.
ERROR: _load: Condition "found" is true. Returned: RES()
   At: core/io/resource_loader.cpp:279.
```
The user also mentioned that it does not happen in their other computer, which also runs Solus OS. It's also worth mentioning that this issue seem to be happening randomly, sometimes it runs succesfuly, others it does not.

**Steps to reproduce:**
I'm not sure yet. This seems random.

**Comment by 20kdc** [comment]
Can confirm the issue happens on Pixelorama 0.8 Linux 64-bit. I am aware that this version is out of date compared to master and does not have the fix commit but just figure it should be known.
Issue is indeed random.
Something to note is that it mentions a sub-resource, not an ext-resource (`brush_button.png` is the latter) and the error message mentions a sub-resource index, not a line number.
