### ISSUE TITLE
Gif Exporting Issue v0.8

### ISSUE THREAD

**Issue by thunderhood277** [Orama-Interactive/Pixelorama#341]
**Pixelorama version:**
v0.8

**OS/device including version:**
Windows 64-bit

**Issue description:**
Exporting stuck on 0%. Program also stops responding when exporting.

**Steps to reproduce:**
100+ frames of animation
Export as animation (.gif file) plus enlarge animation by 500%
Press Ok
Exporting bar (stuck on 0% with no sign of an exported product)

**Comment by jegor377** [comment]
I'm aware of the issue. It didn't come until the release. I'm working to fix it.
