### ISSUE TITLE
Error when deleting a color palette, cannot undo

### ISSUE THREAD

**Issue by carllacan** [Orama-Interactive/Pixelorama#347]
**Pixelorama version:**

v0.8-dev

**OS/device including version:**

Debian 10, no GPU

**Issue description:**

I deleted a color palette and got an error window: "An error occured while removing the palette! Error code: 1"

I could not recover the palette by undoing the action.

**Steps to reproduce:**
Create a new palette, delete it. It doesn't matter if it is empty or not.

**Comment by matthewpaul-us** [comment]
I took a look at v0.8-stable on Win10 and didn't have that issue. I'll retest with dev and see if it shows up there.

**Comment by novhack** [comment]
Most likely will be solved with #356.

**Comment by OverloadedOrama** [comment]
Closing this as undo/redo is tracked in #356.
