### ISSUE TITLE
Cannot run pixelorama in Godot 3.1.1

### ISSUE THREAD

**Issue by azagaya** [Orama-Interactive/Pixelorama#35]
Hi! Idk if this problem is on my side, but when i pulled last changes and try to run it i get this:
![imagen](https://user-images.githubusercontent.com/46932830/70853006-0914d580-1e87-11ea-9218-d4ad061919ee.png)

What could be happening?

**Comment by azagaya** [comment]
It runs in godot 3.2-alpha.. some changes in TranslationServer?

**Comment by Shaderax** [comment]
Just to inform, I have the same problem on my side and so it doesn't just come from your side.
I use godot 3.1

**Comment by Calinou** [comment]
@azagaya Indeed, `TranslationServer.get_loaded_locales()` was added in 3.2 betas and isn't available in 3.1.x.

**Comment by OverloadedOrama** [comment]
Just a little side note here. It actually does run on Godot 3.1.2, which is the version I am currently using.
