### ISSUE TITLE
CMD/CTRL hotkeys 

### ISSUE THREAD

**Issue by KripC2160** [Orama-Interactive/Pixelorama#351]
I wish the program had cmd/ctrl z and cmd/ctrl shift z to undo and redo since having these universal hotkeys makes the workflow much smoother

**Comment by OverloadedOrama** [comment]
Ctrl-Z is already used for undo, and Ctrl-Shift-Z (and Ctrl-Y) for redo. If you're talking about macOS, then this is a duplicate of #67.
