### ISSUE TITLE
Crash after start when sound device changed in the OS

### ISSUE THREAD

**Issue by juan-duarte-a** [Orama-Interactive/Pixelorama#361]
**Pixelorama version:**
v0.8-stable

**OS/device including version:**
Ubuntu 20.04 (Linux version 5.4.0-52-generic) Desktop.

**Issue description:**
Program was launching ok. But after sound output device changed, the program don't start until sound device changed to the previous one.

Crash terminal log in attached file:
[pixelorama_log.txt](https://github.com/Orama-Interactive/Pixelorama/files/5413924/pixelorama_log.txt)

**Steps to reproduce:**
Start Pixelorama for the first time.
Exit Pixelorama.
Change sound device in OS.
Enter Pixelorama.
Crash!
Change sound device in the OS to the previous one.
Start Pixelorama.
Running!

**Comment by OverloadedOrama** [comment]
@Calinou Is this related to #312?

**Comment by Calinou** [comment]
@juan-duarte-a Can you reproduce this if you start Pixelorama with the `--audio-driver PulseAudio` command line argument?

**Comment by juan-duarte-a** [comment]
Same behavior with `--audio-driver PulseAudio`. However, today the behavior has been more erratic, sometimes crashing and sometimes don't with every audio device. I have to try entering the application several times before stop crashing (3 to 5 times to get application started). 

The override doesn't works and it seems Pixelorama starts all times using dummy driver. I got always the same warning and error, even when application initializes:

`ERROR: init_device: Condition "status < 0" is true. Returned: ERR_CANT_OPEN
   At: drivers/alsa/audio_driver_alsa.cpp:83.
WARNING: initialize: All audio drivers failed, falling back to the dummy driver.
   At: servers/audio_server.cpp:215.`

I don't think it is a Godot issue because I use the exact same version of Godot (v3.2.3.stable) and I haven't had this issue at all.

**Comment by Calinou** [comment]
@juan-duarte-a Do you get this issue if you run Pixelorama from the project sources? Clone this repository, import `project.godot`, edit it then run it.

**Comment by juan-duarte-a** [comment]
I don't get the issue if I run Pixelorama from the project sources in Godot. It always starts without problem. 

I realized when I launched Pixelorama (from binaries) and crash, there is this log line that doesn't appear when launched without crashing:

`ERROR: poll: res://src/UI/BrushButton.tscn:18 - Parse Error: Can't load cached sub-resource: res://src/UI/BrushButton.tscn::3
   At: scene/resources/resource_format_text.cpp:528.`

**Comment by juan-duarte-a** [comment]
If I export the project in Godot (runnable Linux/X11 64 bit) I never get the error. The exported application from sources runs very well. Maybe the issue is in the binaries from the web page? (https://orama-interactive.itch.io/pixelorama/purchase)

**Comment by OverloadedOrama** [comment]
> I don't get the issue if I run Pixelorama from the project sources in Godot. It always starts without problem.
> 
> I realized when I launched Pixelorama (from binaries) and crash, there is this log line that doesn't appear when launched without crashing:
> 
> `ERROR: poll: res://src/UI/BrushButton.tscn:18 - Parse Error: Can't load cached sub-resource: res://src/UI/BrushButton.tscn::3 At: scene/resources/resource_format_text.cpp:528.`

This error has been fixed in v0.8.1 (#339). Have you tried updating?

**Comment by juan-duarte-a** [comment]
> This error has been fixed in v0.8.1 (#339). Have you tried updating?

Updated and working fine. Thanks.
