### ISSUE TITLE
Pixelorama crashes when import incorrectly formatted .gpl (GIMP Color Palette) file

### ISSUE THREAD

**Issue by LiquidFun** [Orama-Interactive/Pixelorama#363]
**Pixelorama version:** v0.8.1-stable, from [AUR pixelorama-bin package](https://aur.archlinux.org/packages/pixelorama-bin/)

**OS/device including version:** Arch Linux

**Issue description & steps to reproduce:** 

I created my own palettes using a script and accidentally created an incorrectly formatted .gpl file (note the missing colon after "Columns"):
```
GIMP Palette
Name: Generated Palette
Columns 0
#
244 252 214
```

Readding the colon works as expected, i.e. this is ok:

```
GIMP Palette
Name: Generated Palette
Columns: 0
#
244 252 214
```

Importing the former into Pixelorama causes it to straight up crash.

Only output I get is when running it via terminal, then I see a segmentation fault:
```
$ pixelorama
Godot Engine v3.2.3.stable.official - https://godotengine.org
OpenGL ES 2.0 Renderer: GeForce GTX 750 Ti/PCIe/SSE2
OpenGL ES 2.0 Batching: ON
 
Detected system where we should use XDG basedir standard (currently Linux or BSD)
[1]    111675 segmentation fault (core dumped)  pixelorama
```

I doubt this happens all that often, but I guess it still shouldn't crash?

**Comment by OverloadedOrama** [comment]
Thanks for reporting, I just pushed a fix for this issue. Feel free to try it by downloading the dev builds from the Actions page, once they're generated.

**Comment by LiquidFun** [comment]
Thanks for the quick response! Will do :)
