### ISSUE TITLE
When swapping colors a fully transparent color (alpha=0) is changed to be fully opaque (alpha=255)

### ISSUE THREAD

**Issue by LiquidFun** [Orama-Interactive/Pixelorama#364]
Alright, it's me again :D

**Pixelorama version:** v0.8.2-dev, Commit "Fixes #363" (df7a650) (latest)

**OS/device including version:** Arch Linux

**Issue description:**

If one of the colors is fully transparent when swapping between the left-tool color and right-tool color it will become fully opaque.

**Steps to reproduce:**

Click on one color and drag the alpha slider to 0, then press x or on the two-sided arrows to swap the colors.

I see why it happens here:
https://github.com/Orama-Interactive/Pixelorama/blob/df7a65013718628b660215a222415abaae6e5553/src/Autoload/Tools.gd#L122-L129

But I can't say I understand the reasoning behind that if statement? At least the swapping behaviour is not what one might expect from other software.

**Comment by OverloadedOrama** [comment]
I think that this behavior comes from suggestion #54, but I did not realize that this piece of code also affects swapping. I will fix this so swapping will work as intended.
