### ISSUE TITLE
Dialogue button text does not change after switching language

### ISSUE THREAD

**Issue by timothyqiu** [Orama-Interactive/Pixelorama#371]
**Pixelorama version:** 0.8.1 stable

**OS/device including version:** Not graphics related

**Issue description:**
If I start Pixelorama in a CJK language and then switch it to a non-CJK language: The title and button text of dialogues won't change.

Text of the close button:
![close button](https://user-images.githubusercontent.com/372476/97142555-c8baff00-179b-11eb-8958-df438775920a.png)

Text of the buttons and title:
![dialogue buttons and title](https://user-images.githubusercontent.com/372476/97142558-c9ec2c00-179b-11eb-9dc0-9d6fdd7f0938.png)

It works fine if I start Pixelorama in non-CJK language, and then switch the language back and forth.

**Steps to reproduce:**
1. Switch to Simplified Chinese in Edit - Preferences - Language (any CJK language will do)
2. Restart Pixelorama
3. Switch the language back to English

**Comment by Kinwailo** [comment]
this is a bug in godot:
https://github.com/godotengine/godot/issues/39320

**Comment by OverloadedOrama** [comment]
https://github.com/godotengine/godot/issues/39320 is closed now, but the PR that closed it seems to be only for 4.0. However, I can no longer replicate the issue, so I assume it has been fixed in 3.x as well, therefore I think it should be safe to close this issue now.
