### ISSUE TITLE
Wishlist: armv7 and aarch64 Linux builds

### ISSUE THREAD

**Issue by tidux** [Orama-Interactive/Pixelorama#373]
**Feature/enhancement description:**
Pixelorama is already available on Flathub with an official package, which is great!  Adding armv7 and aarch64 (32 bit and 64 bit ARM) builds would make the Raspberry Pi or other ARM devices a solid choice for making pixel art.  It would even help with ChromeOS, since there are ChromeOS ARM devices that can run flatpaks.

**Comment by Pumpkinwaffle** [comment]
Did you try FRT?

https://github.com/efornara/frt

**Comment by ragreenburg** [comment]
@Pumpkinwaffle  How would FRT help? I know it is basically Godot for ARM but how would one be able to run Pixelorama off of that?

**Comment by Pumpkinwaffle** [comment]
Well pixelorama is made in Godot. FRT is your best shot at getting it to run on arm.

Download the pixelorama source code, open it in Godot and use the export templates provided by FRT.

I've gotten a quite a few godot projects running on my Linux arm handheld with it.

Depends on the device you want to run it on. I belive someone compiled the godot engine for raspberry pi as well. If FRT doesn't work you can always try that.

**Comment by ragreenburg** [comment]
Interesting, thanks for the tip. I'll give that a go. If it happens to work I will try to ping the devs on it or I'll host an unofficial raspberry pi version. I noticed there was an unofficial godot version for raspberry pi but I also haven't used it yet. 

https://github.com/hiulit/Unofficial-Godot-Engine-Raspberry-Pi
