### ISSUE TITLE
Trasparency checker size is doubled

### ISSUE THREAD

**Issue by crawfxrd** [Orama-Interactive/Pixelorama#377]
**Pixelorama version:**

Tested on:
- 0.8.1-stable
- fad41bd27ba9b576e6d5d51cd9d3c058f6b24385

**OS/device including version:**

Fedora 33

**Issue description:**

Expected: Checker size uses value specified
Actual behavior: Checker size is twice the set value (e.g. 6 px when set to 3 px)

**Steps to reproduce:**

- Set checker size to 1
- Set follow canvas movement
- Set follow zoom level
- Zoom in on canvas

![Screenshot from 2020-11-07 20-08-01](https://user-images.githubusercontent.com/5222085/98456086-4ab10d80-2136-11eb-9a47-1b75bb1e1f2d.png)

**Comment by crawfxrd** [comment]
Playing around with it more, I have at least 2 more issues with these settings:

- Selecting 'Image > Resize Canvas' and not changing anything causes the scaling of the board to change to some strange value (25 checkers for 8 px)

![Screenshot from 2020-11-08 00-33-04](https://user-images.githubusercontent.com/5222085/98459646-03d50f00-215a-11eb-9e8f-2842ca6a9bbc.png)

- Adding a new layer on a non-square canvas stretches the transparency checker board

![Screenshot from 2020-11-08 00-35-55](https://user-images.githubusercontent.com/5222085/98459694-61695b80-215a-11eb-9920-c5e798f338d7.png)

**Comment by abhinav3967** [comment]
transaprency checker stretching while exporting

![image](https://user-images.githubusercontent.com/62714538/99038298-3c864580-25ab-11eb-8cce-515a6da2eecc.png)
