### ISSUE TITLE
Issue from translations 

### ISSUE THREAD

**Issue by KripC2160** [Orama-Interactive/Pixelorama#383]
**Pixelorama version:**
v0.8.1-stable

**OS/device including version:**
MacOs Catalina version 10.15.4 / MacBook Air (13-inch, early 2015) / Intel HD Graphics 6000

**Issue description:**
I tried to use language as Korean and spotted this 

![Uploading Screen Shot 2020-11-16 at 18.11.54.png…]()

I did see it was already translated in crowdin and seems like a bug 

![Screen Shot 2020-11-16 at 18 11 46](https://user-images.githubusercontent.com/65854891/99234359-c4807f80-2837-11eb-9656-94e8e156ea41.png)

**Steps to reproduce:**

**Comment by KripC2160** [comment]
Edit: Screen shot of the bug it did not upload for some reasons 
![Screen Shot 2020-11-16 at 18 11 54](https://user-images.githubusercontent.com/65854891/99234661-2b059d80-2838-11eb-98be-3337a4528d3b.png)

**Comment by OverloadedOrama** [comment]
Thanks for reporting. This bug has already been fixed in the master branch (0d5b4416a4aa7919e41cfb0d2a9c9fa3c1da194a), and will be included in v0.8.2. You can see it fixed in an [early access version](https://orama-interactive.github.io/Pixelorama/early_access/)!

**Comment by KripC2160** [comment]
thanks for letting me know!
