### ISSUE TITLE
The program sometimes frozen in the canvas area.

### ISSUE THREAD

**Issue by magic-element-k** [Orama-Interactive/Pixelorama#392]
**Pixelorama version:** 0.8.1

**OS/device including version:**
Windows 10 Pro / GeForce GTX 1650 super

**Issue description:** 
Sometimes the Pencil tool freezes at the edges of the mesh even when the mesh is turned off. The program does not freeze completely, only in the canvas area. In this case, it is restored in about a minute or a few minutes, or you can perform any action, for example, change the color or select the color that was (after which the problem disappears immediately, until you click again with a pencil in the same place). When everything is restored, if you click on the same spot again, the canvas will freezes again. And so several times in a row.
This happens randomly.

**Steps to reproduce:**

1. I choose the pencil tool.
2. I click on the canvas next to the grid line - the canvas freezes.
3. Selects a color - the canvas works again (you can paint again).
4. I click anywhere on the canvas with a pencil - it doesn't freeze.
5. I click on the pixel where the freeze occurred - the canvas is freezes.

**Comment by OverloadedOrama** [comment]
If I understand correctly, this issue should have been fixed in v0.8.2-dev. Can you try an early access version ([download](url) or use the [Web version](https://orama-interactive.github.io/Pixelorama/early_access/)) and tell me if the problem still occurs?

**Comment by OverloadedOrama** [comment]
This has most likely been fixed now.
