### ISSUE TITLE
"no mountable file systems"

### ISSUE THREAD

**Issue by FutureMixUp** [Orama-Interactive/Pixelorama#395]
After downloading `Pixelorama.Mac.dmg` from the `0.8.5` release page and opening it, it tells me that there are "`no mountable file systems`" in the `.dmg`:

![pixelorama_mac_no_mountable_file_system](https://user-images.githubusercontent.com/69090085/101376097-739cfd80-38b0-11eb-80e3-e45183ea76b6.png)

Looking at the console, when opening the `.dmg`, I get
```
CoreServicesUIAgent[43880]: Error -60005 creating authorization
```

and

```
xpcproxy[43968]: CFPreferences could not connect to its daemon.
Preferences using the connection 0x0 will be volatile and will not be persisted to disk.
```

Now I'm not __*that*__ good with coding and programmation in general, especially at this kind of level, so I'm a bit confused:
Is this a problem with the file itself, or is it my computer that isn't good enough (*too old* or something like that)?

Thanks in advance!

**Comment by Schweini07** [comment]
First which version of MacOS are you using?
I assume below Catalina, as this issue seems to be present in version below 1.15.

Try this .dmg please: https://docs.google.com/uc?export=download&id=1VZyz82ezuH_SHxdGpLTGdUmKYl7KsECU

It's compiled under Yosemite and should work.

**Comment by FutureMixUp** [comment]
Thank you so much @Schweini07 for the quick response!

I'll try this as soon as I can and get back to you right after.

Thanks again!

**Comment by FutureMixUp** [comment]
@Schweini07 Thank you so much!

It works just fine, it was indeed a version problem after all.
Thanks again, have a nice day/evening! :D

**Comment by FutureMixUp** [comment]
Then I think this issue can be closed now.

**Comment by Schweini07** [comment]
That's great news!

Still I would be interested what's causing this. But that's something for another time.

**Comment by FutureMixUp** [comment]
I think my computer simply was too old for this version (OSX 10.11)
