### ISSUE TITLE
(Linux) Unable to Copy or Paste

### ISSUE THREAD

**Issue by Nalucap** [Orama-Interactive/Pixelorama#438]
Unable to copy or paste, tried both keyboard shortcuts and from the Edit toolbar.
Cutting seems to erase selected areas but it also doesn't put it on the clipboard.

**Pixelorama Versions:** 0.8.2 and 0.8.1 (Flatpak)
**Operating System:** Linux Mint 20.0

**Comment by OverloadedOrama** [comment]
This is probably not a bug, but the result of the current selection system being unintuitive. You need to have made a selection first before pasting, otherwise paste does nothing. This is scheduled to change in v0.9, see #129 for the proposal of the new selection system.
