### ISSUE TITLE
Would it be possible to add a deselect shortcut

### ISSUE THREAD

**Issue by indignant** [Orama-Interactive/Pixelorama#449]
**Pixelorama version:**
v0.8.2-stable

**OS/device including version:**
OSX Catalina 10.15.7

**Issue description:**
It's very difficult to deselect after using the rectangle selection tool. In Preferences -> Shortcuts there's not a shortcut listed for deselect. `esc` and `delete` don't do anything. Searching for a shortcut does not return results.

So I guess the issue is either:
1. There's not a quick way to deselect a selection
2. There's no documented way to deselect a selection

**Steps to reproduce:**
1. Use the rectangle selection tool to select something
2. Note that there's not an intuitive way to deselect

Thanks for making Pixelorama, it's a fun piece of software!

**Comment by abhinav3967** [comment]
Hello,
The selection tool is being rewritten for the next update. This might be implemented in it.

**Comment by OverloadedOrama** [comment]
Sorry, I forgot to close this issue. A deselect shortcut was implemented in #457 and this change will be included in the next version! There's still not a way to change the shortcut, but there will most likely be in a future update (see #309)
