### ISSUE TITLE
The master branch is broken right now

### ISSUE THREAD

**Issue by SbNanduri** [Orama-Interactive/Pixelorama#46]
I think #41 added some new nodes in the scripts but forgot to commit the actual nodes. These nodes don't exist:
```
 	add_palette_button = find_node_by_name(root, "AddPalette")
	remove_palette_button = find_node_by_name(root, "RemovePalette")
	palette_option_button = find_node_by_name(root, "PaletteOptionButton")
	edit_palette_button = find_node_by_name(root, "EditPalette")
	palette_container = find_node_by_name(root, "PaletteContainer")
```

**Comment by OverloadedOrama** [comment]
Hello, these nodes do exist on the Main scene.
![image](https://user-images.githubusercontent.com/35376950/70865178-1f905f00-1f63-11ea-833e-15cb1ed8c03f.png)

**Comment by SbNanduri** [comment]
oh that's weird, I have it now. Maybe I had to restart Godot for that to work. Sorry about that, thanks!
