### ISSUE TITLE
Line-Erase does not highlight 

### ISSUE THREAD

**Issue by KripC2160** [Orama-Interactive/Pixelorama#464]
**Pixelorama version:**
v0.8.2

**OS/device including version:**
Pop! OS 

**Issue description:**
Erase tool also has a convenient tool like pen tool which is to hold shift to perform line tool. However, the highlight of the blue box only shows when using the pen tool but not erase tool. Erase tool with SHIFT key works fine, it's just the highlight does not show. 

**Steps to reproduce:**
use erase tool and press shift to erase as if you are making a line using the tool and it works

**Comment by Variable-ind** [comment]
are you using eraser as a left tool or a right tool? if the eraser is in the right tool then you would have to enable highlighting in the
"Edit>Preferences>Indicators>Right Pixel Indicater"

**Comment by KripC2160** [comment]
oh sorry I was using the right mouse.
