### ISSUE TITLE
macOS show pixel grid hotkey conflicts with system hotkey

### ISSUE THREAD

**Issue by kalenpw** [Orama-Interactive/Pixelorama#493]
**Pixelorama version:**

v0.8.3-stable

**OS/device including version:**

macOS 10.14.16

**Issue description:**

On macOS command + h is a system wide shortcut to hide the current window, so it can't be used to toggle show the pixel grid

**Steps to reproduce:**

1. Open Pixelorama on a Mac
2. Press command + h
3. Window will hide and pixel grid will remain in the current state when it is reopened

I don't really have a suggested fix for this (nor am I bothered by it). If you close as won't fix I won't be offended, just figured I would point it out in case you weren't aware.

**Comment by Variable-ind** [comment]
Currently there is no way to fix it (except change the button for "show_pixel_grid" in the source code). However there are plans to make all shortcuts customizable in one of the future updates
