### ISSUE TITLE
Crash when adjusting the Hue/Saturation/Value

### ISSUE THREAD

**Issue by kalenpw** [Orama-Interactive/Pixelorama#495]
**Pixelorama version:**
v0.8.3-stable

**OS/device including version:**
Ubuntu 20.04

**Issue description:**
When using the Image > Adjust Hue/Saturation/Value menu option. I can reliably crash the program by adjusting sliders until after a few seconds it crashes.

Console output below:
```
Godot Engine v3.3.stable.official - https://godotengine.org
OpenGL ES 2.0 Renderer: Mesa Intel(R) UHD Graphics 620 (KBL GT2)
OpenGL ES Batching: ON
 
Detected system where we should use XDG basedir standard (currently Linux or BSD)
ERROR: texture_set_data: Condition "!read.ptr()" is true.
   At: drivers/gles2/rasterizer_storage_gles2.cpp:716.
ERROR: texture_set_data: Condition "!read.ptr()" is true.
   At: drivers/gles2/rasterizer_storage_gles2.cpp:716.
ERROR: texture_set_data: Condition "!read.ptr()" is true.
   At: drivers/gles2/rasterizer_storage_gles2.cpp:716.
ERROR: texture_set_data: Condition "!read.ptr()" is true.
   At: drivers/gles2/rasterizer_storage_gles2.cpp:716.
ERROR: create_from_image: Condition "p_image.is_null() || p_image->empty()" is true.
   At: scene/resources/texture.cpp:199.
free(): corrupted unsorted chunks
[1]    58994 abort (core dumped)  ./Pixelorama.x86_64
```

**Steps to reproduce:**

1. Create 16x16 image
2. Paint stripes of any color
3. Open adjust hue/saturation/value menu
4. Randomly slide dials back and forth 
5. After a few seconds crash will happen

If useful I can record a screen recording of it too.

**Comment by OverloadedOrama** [comment]
#475 has changed how HSV works by using a shader. This should also have fixed cases where HSV adjusting caused crashes. Can you either test cloning the repository's master branch or download an early access v0.9 binary from https://nightly.link/Orama-Interactive/Pixelorama/workflows/dev-desktop-builds/master to see if this issue can still get replicated? Thanks!

**Comment by kalenpw** [comment]
Sweet, I actually saw that issue, but thought it was merged into the version I had for some reason.

I can confirm on v0.9 it works great (and the other change are nice too!)
