### ISSUE TITLE
error importing a valid gimp palette file

### ISSUE THREAD

**Issue by Ryder17z** [Orama-Interactive/Pixelorama#502]
**Pixelorama version:**
0.8.3 (snap)

**OS/device including version:**
Manjaro Linux 21.0.7

**Issue description:**
![image](https://user-images.githubusercontent.com/2000703/123511264-a6f27e80-d680-11eb-902a-e0794a45d85e.png)

it should correctly import this file of about 730 colors.
GIMP loads it without complaints:
![image](https://user-images.githubusercontent.com/2000703/123511635-b2df4000-d682-11eb-9319-0845d8abcd86.png)

**Steps to reproduce:**
Try to import this file into Pixelorama:
[color_palette.pal.txt](https://github.com/Orama-Interactive/Pixelorama/files/6720009/color_palette.pal.txt)

**Comment by OverloadedOrama** [comment]
This doesn't seem to be a valid .pal file. .pal palette files start with "JASC-PAL" as their first line (source: https://liero.nl/lierohack/docformats/other-jasc.html). This is actually a .gpl file. Changing the file extension from .pal to .gpl and then importing this to Pixelorama seems to be working fine. But if desired, we could add a way to detect an invalid .pal file and try to import it as a .gpl instead, so you wouldn't have to change the file's extension.

**Comment by Ryder17z** [comment]
ooops. but yes. automatically determine format by file header would be nice.

**Comment by novhack** [comment]
I added the palette header detection to future enhancements of the palette system. It will be tracked here #356 so I guess this issue can be closed.
