### ISSUE TITLE
'"Pixelorama.app” is damaged and can’t be opened. You should move it to the Bin.' on latest MacOS version.

### ISSUE THREAD

**Issue by EinoHR** [Orama-Interactive/Pixelorama#516]
**Pixelorama version:**
0.8.3 from Github Releases MacOS version. Does not happen on 0.8.2.

**Issue description:**
First installed from brew (installs from github releases), got the error message `“Pixelorama.app” is damaged and can’t be opened. You should move it to the Bin.`. Thought that it was a problem with brew, but installing manually has the same problem.

**Steps to reproduce:**
1. Download and open Pixelorama.Mac.dmg
2. Move it to Applications
3. Try to open it

**Comment by Variable-ind** [comment]
Hy,
There are similar issues like #264 and #240, try following these instructions to see if it works 

> After you extract the .zip file, right-click on the .app file >choose Open in the dropdown then click Open in the warning dialog. Alternatively, you can right click the .app > show package contents, then open a terminal inside its Contents/MacOS folder. Then, type chmod +x Pixelorama . Go back to the .app file and you can now open it normally."

**Comment by EinoHR** [comment]
`chmod +x` Didn't work but disabling gatekeeper using these instructions worked. https://disable-gatekeeper.github.io/

**Comment by OverloadedOrama** [comment]
Thanks for the reporting this issue. Unfortunately, there's not much we can do without signing the app, which requires $99 annual payments to Apple. The only way to get around this, like you mentioned, is disabling gatekeeper.

**Comment by haz-ai** [comment]
Found a workaround
If you download and build from source code it will work with your Apple ID.
Would it be possible to publish build instructions or are they just the defaults?
also would steam not be an option

**Comment by ReyAnthony** [comment]
Actually I'm pretty sure it's a packaging issue : 

- Adding executable rights to the binary in the app is not working 
- App are normally shown inside the security pane to be allowed if gatekeeper blocked them 
- gatekeeper cannot be disabled on m1 macs

**Comment by MinecraftPublisher** [comment]
Recommendation:
1. On the `.app` file, Right click and select show package contents
2. Copy the whole `Contents` folder
3. Create a new folder somewhere else on your Desktop or wherver else, Name it `Pixelorama.app`, And when it prompts to add the `.app` extension, Click Add.
4. Right click on the newly created folder/file, And press show package contents.
5. Paste the Contents folder you copied from before.
6. And... You are done! By doing this your computer assigns that file a "safe" tag that makes your system run the new file correctly.

**Comment by bruvzg** [comment]
To avoid `X is damaged and can’t be opened.` error, app can be `ad-hoc` signed (signed without Apple ID) using `codesign -s - --force --deep ./pixelorama.app` command.

See https://docs.godotengine.org/en/latest/tutorials/export/running_on_mac.html, for all possible Gatekeeper errors and workarounds.

**Comment by OverloadedOrama** [comment]
> To avoid `X is damaged and can’t be opened.` error, app can be `ad-hoc` signed (signed without Apple ID) using `codesign -s - --force --deep ./pixelorama.app` command.
> 
> See https://docs.godotengine.org/en/latest/tutorials/export/running_on_mac.html, for all possible Gatekeeper errors and workarounds.

Thank you for the suggestion! I made a PR for this change (#602), can someone download the generated build and confirm that the issue is solved?

**Comment by Priti-Palkar** [comment]
Hey there I wanna work on this. Can you assign it to me?

Thank you

**Comment by 31d4r** [comment]
1. Remove the quarantine attribute (use the path where the app actually is. It’s often in /Applications, not ~/Applications):
```sh
xattr -dr com.apple.quarantine /Applications/Pixelorama.app
```
If you installed it somewhere else, replace /Applications/Pixelorama.app with the full path to the app.

2. Open the app:
```sh
   open /Applications/Pixelorama.app
```
Or in Finder: right-click the app, choose Open, then click Open in the dialog. That tells macOS you trust the app.
If you get "No such file": You’re probably in the wrong folder. Check both:

- /Applications (main Applications folder)
- ~/Applications (your user Applications folder)

Use the full path in the xattr command, e.g. /Applications/Pixelorama.app.

**Comment by KyNorthstar** [comment]
Pixelorama is being removed from Homebrew now because of this.

<img width="603" height="202" alt="Image" src="https://github.com/user-attachments/assets/9560b69c-3357-4038-b5a7-02c310abc9e6" />

**Comment by lpjune** [comment]
Easiest way to fix this with no other installs necessary, sign it yourself
Make sure Pixelorama is in your Applications directory, then:

sudo xattr -cr /Applications/Pixelorama.app
find /Applications/Pixelorama.app -name "._*" -delete
find /Applications/Pixelorama.app -name ".DS_Store" -delete
sudo codesign --force --deep --sign - /Applications/Pixelorama.app
