### ISSUE TITLE
Version 0.8.3 seems tagged from the wrong commit

### ISSUE THREAD

**Issue by akien-mga** [Orama-Interactive/Pixelorama#521]
**Pixelorama version:**
Tag `v0.8.3`: https://github.com/Orama-Interactive/Pixelorama/releases/tag/v0.8.3
Commit 5f84629144f8e214830d839eb66e9ca862fa65a6

**OS/device including version:**
Linux

**Issue description:**
I was looking at updating my Mageia package for Pixelorama from 0.8.2 to 0.8.3, when I noticed that the `config/Version` said `0.9-dev`.

It seems like the `v0.8.3` tag was tagged on the wrong branch, as it was made from `master` and not from `0.8`.

It suppose `v0.8.3` was meant to be tagged from this commit instead?
https://github.com/Orama-Interactive/Pixelorama/commit/2d9ddad9268e267618f264b0608dadca2763f5f3

I assume that the binaries themselves were properly built from `0.8`, so it's only the Git tag and the generated tarballs which are wrong. Might be worth deleting and redoing the tag to avoid confusion.

**Steps to reproduce:**
n/a

**Comment by OverloadedOrama** [comment]
Sorry, looks like I had messed something up back then. I think I have fixed it now (deleted the tag and re-made it), can you confirm?

**Comment by akien-mga** [comment]
Yes, I confirm it's good now. Thanks!
