### ISSUE TITLE
UX Recommendation: Move color preview under color picker

### ISSUE THREAD

**Issue by tiritto** [Orama-Interactive/Pixelorama#53]
Hello! I would like to recommend rather simple UX improvement, namely I recommend moving color preview down, placing it in between RGBA sliders and color picker itself.

**How would this change be beneficial?**
1. In vast majority of software that utilizes color pickers there is nothing else above (or at least nothing interactive that might require user attention) color palette. As the result, a lot of people might instinctively ignore this part of the window on their first contact with Pixelorama.

2. By placing color preview right between color picker and color RGBA sliders, sliders become easier to use as user can keep an eye on both sliders and current color preview at the same time without need to "jump" over large space that color picker creates.

3. As color preview is placed in a spot that is easy to notice even without having direct attention on it, user will be able to notice undesired transparency settings "on the occasion" of adjusting color hues. 

**Concept preview:**
![Color Preview](https://user-images.githubusercontent.com/5196829/70875589-b5090e80-1fb6-11ea-89c5-b346438668ab.png)

**Comment by Calinou** [comment]
This could also be worth changing in Godot itself. I'll look into it.
