### ISSUE TITLE
Merging layer with opacity < 100% causes crash

### ISSUE THREAD

**Issue by mrtripie** [Orama-Interactive/Pixelorama#541]
**Pixelorama version:**

0.9

**OS/device including version:**

Widows 10
Gtx 1060 6GB

**Issue description:**

If you merge a layer that has a cel with < 100% opacity with the layer below, Pixelorama will crash.

**Steps to reproduce:**
1: make a file
2: add a layer
3: adjust opacity to less than 100%
4: merge with layer below.

**Comment by Variable-ind** [comment]
I quick tested the web version, i can't seem to reproduce the bug (does it happen on web as well?)

**Comment by mrtripie** [comment]
Doesn't crash in web editor, however, if I draw in the semi transparent layer there, and merge it, it won't take the opacity into account when merging.

**Comment by Variable-ind** [comment]
Nevermind i found the bug..., There needs to be `selected_layer.lock()` added at **line 529** of **AnimationTimeline.gd**

**Comment by mrtripie** [comment]
That sounds likely to be what would fix the crash, will it also merge with the correct level of opacity?

Here's what I mean in the web editor, the blue square is merged in with 100% opacity when I wanted it to be merged in semi transparently:

https://user-images.githubusercontent.com/65431647/134403708-99e29281-739f-41bf-ac6c-a1f8f77fdb10.mp4

**Comment by Variable-ind** [comment]
yeah, `selected_layer.lock()` fixes the crash along with transparency
