### ISSUE TITLE
Palette Panel Disappear After Using Show Desktop on Windows 10

### ISSUE THREAD

**Issue by CIOSAI** [Orama-Interactive/Pixelorama#547]
**Pixelorama version:**

0.9

**OS/device including version:**

Windows 10

**Issue description:**

When using the show desktop button (the button that minimized all programs), the palette panel goes to the right, outside of the program display area. This does NOT happen when clicking the minimize button of Pixelorama, that part works fine. It happens specifically with show desktop button.

**Steps to reproduce:**
1. Open Pixelorama program
2. click the show desktop button (bottom right most)
When it's normal
![ttttttttttttttt](https://user-images.githubusercontent.com/89374056/136696371-bc583e98-18e7-44e6-9358-4e89dd09a9e9.png)
After minimizing with show desktop button
![tbyet](https://user-images.githubusercontent.com/89374056/136696378-d09d4bcd-1513-4628-97f9-864a35c935c3.png)

**Comment by OverloadedOrama** [comment]
I can no longer replicate this issue on v0.10, so I assume it has been fixed due to the new UI system.
