### ISSUE TITLE
Feature: Color switch while holding a keyboard button

### ISSUE THREAD

**Issue by novhack** [Orama-Interactive/Pixelorama#55]
With a pencil on a left mouse button and a color picker on the right it would be nice to be able to quickly pick a color for a pencil with the picker.
My proposal is to bind one of the keyboard buttons to switch colors while it's being held and to switch them back when released. I think that with a current "switch colors" functionality it could be an easy feature to implement.
I also propose that it could be `ctrl` button, because `shift` in this case shows a line guide and `alt` button is in the most of Linux distributions used for window manipulation.

**Comment by Calinou** [comment]
In graphics editing applications, <kbd>X</kbd> is a common shortcut to swap the primary and secondary colors, but it usually works in a "toggle" basis, rather than on a "hold" basis as you mentioned.

**Comment by OverloadedOrama** [comment]
I implemented `Ctrl-X` as a shortcut for color switching in b377dfa98bd427e8fe47bc960eb14c403e3a0ddd. Is this sufficient?

**Comment by Calinou** [comment]
@OverloadedOrama I think just <kbd>X</kbd> makes more sense for this, as <kbd>Ctrl + X</kbd> will likely be used for cutting at some point.

**Comment by OverloadedOrama** [comment]
That's a fair point. I'm changing it now.
