### ISSUE TITLE
Crashes when drawing and switching tools using shortcuts

### ISSUE THREAD

**Issue by PatrickDorneles** [Orama-Interactive/Pixelorama#618]
**Pixelorama version: 
0.9

**OS/device including version: 
Ubuntu 20.04
Intel Iris(R) Plus Graphics

**Issue description: 
Crashes on switching some tools using the keyboard shortcuts while drawing. 
It crashes when switching from any other tool to pen, eraser or shading.

**Steps to reproduce: 
1. Pick any tool
2. Start drawing or selecting
3. While holding down the mouse button (or the pen on the drawing tablet) try to switch to the pen, eraser or shading tool using its keyboard shortcut
4. Pixelorama will stop working

**Comment by OverloadedOrama** [comment]
Thanks for reporting, I think I have fixed it now in the master branch and the fix will be included in version 0.9.1. If you'd like, you can try to download the [release candidate version](https://nightly.link/Orama-Interactive/Pixelorama/workflows/dev-desktop-builds/master) or the [Web version](https://orama-interactive.github.io/Pixelorama/early_access/) to see if you can still reproduce the issue.
