### ISSUE TITLE
Broken mirrored drawing

### ISSUE THREAD

**Issue by yaboy365** [Orama-Interactive/Pixelorama#626]
**Pixelorama version:**
0.91

**Issue description:**

After opening previously made projects and enabling mirrored drawing, both mirror lines appear at the default 32px from the left and 32px from the top, even with larger dimensions.

**Steps to reproduce:**
1. Create new file with dimensions larger than 64x64 (I did 256x256)
2. Save file as .pxo.
3. Close and launch Pixelorama again.
4. Open previously saved file.

**Comment by Variable-ind** [comment]
yeah, it seems the bug is in Project.gd i changed the following lines and it seems to work
![lines](https://user-images.githubusercontent.com/77773850/147874091-877f75e3-0e85-46c6-b594-30ee1c691a17.png)

**Comment by Variable-ind** [comment]
it seems we can only **get** but *not* **change** values using the first method

https://user-images.githubusercontent.com/77773850/147874544-f5008fa7-f074-473e-9c74-0d537deda02f.mp4

**Comment by OverloadedOrama** [comment]
Thanks for reporting, the fix for this bug will be included in v0.9.2. And thank you @Variable-ind for the solution!
