### ISSUE TITLE
Russian localization

### ISSUE THREAD

**Issue by AndreevAndrei** [Orama-Interactive/Pixelorama#63]
Add russian localization

**Comment by AndreevAndrei** [comment]
Not all words are wrapped to `tr()` but mostly looks good
Also I've got a little trouble to show russian language in properties `list-box` (I've test it on `pl`)

**Comment by OverloadedOrama** [comment]
Hello, thanks for the translation! I added the Russian language under Preferences. I'm just not sure what the best word for "Russian" in Russian is. I put русский [ru]. Is this correct?

**Comment by AndreevAndrei** [comment]
yep! Русский [ru] is perfect! :)

вт, 17 дек. 2019 г. в 14:11, Overloaded <notifications@github.com>:

**Comment by AndreevAndrei** [comment]
but the first letter upper case would better (р -> Р)

**Comment by OverloadedOrama** [comment]
I fixed it in 7dd67e71306cca8165886338cd68a2f0455ab28a :)
