### ISSUE TITLE
[Ubuntu Touch] Crash on Pixel 3a Sargo after ver. 0.9.2 stable release

### ISSUE THREAD

**Issue by mattbel10** [Orama-Interactive/Pixelorama#637]
It crashes now on Pixel 3a, while before used to work fine.
Errors log is here below attached:
`[1;31mERROR: try_open_pack: [0m[1mMethod failed. Returning: false
[0;31m   At: core/io/file_access_pack.cpp:190.[0m
[1;31mERROR: _setup: [0m[1mCondition "!ok" is true. Returned: ERR_CANT_OPEN
[0;31m   At: core/project_settings.cpp:349.[0m
Error: Couldn't load project data at path ".". Is the .pck file missing?
If you've renamed the executable, the associated .pck file should also be renamed to match the executable's name (without the extension).
[1;31mERROR: try_open_pack: [0m[1mMethod failed. Returning: false
[0;31m   At: core/io/file_access_pack.cpp:190.[0m
[1;31mERROR: _setup: [0m[1mCondition "!ok" is true. Returned: ERR_CANT_OPEN
[0;31m   At: core/project_settings.cpp:349.[0m
Error: Couldn't load project data at path ".". Is the .pck file missing?
If you've renamed the executable, the associated .pck file should also be renamed to match the executable's name (without the extension).
[1;31mERROR: try_open_pack: [0m[1mMethod failed. Returning: false
[0;31m   At: core/io/file_access_pack.cpp:190.[0m
[1;31mERROR: _setup: [0m[1mCondition "!ok" is true. Returned: ERR_CANT_OPEN
[0;31m   At: core/project_settings.cpp:349.[0m
Error: Couldn't load project data at path ".". Is the .pck file missing?
If you've renamed the executable, the associated .pck file should also be renamed to match the executable's name (without the extension).
`

**Comment by OverloadedOrama** [comment]
Closing as Ubuntu Touch is no longer a supported platform. Version 1.0 will have Linux ARM builds for both 32 and 64 bit, so hopefully Linux phones will be able to use these. Android is also planned for some time in the future.

**Comment by Fuseteam** [comment]
will the arm build be debs by any chance?

**Comment by Fuseteam** [comment]
I see what you mean now, i'll test again to see if we can use these
