### ISSUE TITLE
Everything is small (no window scaling)

### ISSUE THREAD

**Issue by Pelle-Reimers** [Orama-Interactive/Pixelorama#643]
**Pixelorama version:**
v0.9.1-stable

**OS/device including version:**
Ubuntu 20.04

**Issue description:**
When I first started the program after install, everything was very small. While there is a display size setting, getting there is hard because.... everything is so small!

![image](https://user-images.githubusercontent.com/87088722/151715844-11f21068-e145-461d-8869-d53e7e677e21.png)

**Steps to reproduce:**
* Have a screen size of 3840 × 2160.
* Have the OS screen scale set to 200%, since everything is so small.
* Add an additional 1.25 font scaling using Gnome Tweaks, since text is still hard to read.
* Install and start Pixelorama.
* Have a hard time seeing where the display size settings are since the GUI is so small and dark/low contrast.

**Comment by OverloadedOrama** [comment]
You can scale the UI from the Preferences (https://orama-interactive.github.io/Pixelorama-Docs/troubleshooting#i-have-a-hidpi-monitor-and-the-user-interface-is-very-small), doesn't that fix the issue?

**Comment by Pelle-Reimers** [comment]
Yes, but getting there is hard because everything is so small. I'm mainly thinking about first time user experience here.

**Comment by azuredusk10** [comment]
I agree with @Pelle-Reimers.

I downloaded Pixelorama for the first time via Flathub. When I saw the UI was tiny, I assumed this was another program which didn't scale properly on high pixel density screens, and thought it was a shame I wasn't going to be able to use it.

If I hadn't come on Github and read that there was a UI scaling option, I wouldn't have known I could use the program.

A sensible default would be great for Linux users with scaling turned on. I had the same issue on Fedora 35, running Gnome on Wayland, with 200% scaling. This is what I saw for the first time:

![image](https://user-images.githubusercontent.com/18142893/161452144-0b74076e-d87f-4eec-bcc6-11261a354ded.png)

(Thanks for your hard work on this program, I can't wait to give it a try now!)

**Comment by OverloadedOrama** [comment]
I implemented UI auto-scaling based on the monitor resolution and dpi (in commit d69d98dc3be6bbc30daf00a6fcfdf581360eecb0), so the issue should probably be considered resolved now. I haven't tested it myself because I do not own a hiDPI monitor, but the code is taken directly from Godot's editor, so it has been tested there and I assume it works well. The change will be included in the next version.

**Comment by azuredusk10** [comment]
I can confirm that the fix works! From a fresh install with no previous user data, Pixelorama now loads up with the UI scaled 2x on my machine the first time I opened it. Thank you for this!
