### ISSUE TITLE
Multiple scaling issues

### ISSUE THREAD

**Issue by rongcuid** [Orama-Interactive/Pixelorama#663]
**Pixelorama version:**
Flatpak version 0.9.2

There are multiple issues related to scaling:

1. When UI is scaled, IBus candidate window is at the wrong location, as if it it scaled at 100%
    * That is, if scaling is 200% and text input is at point P, the candidate window appears halfway between P and top-left corner
2. When UI is scaled, color picker actually picks color from point of inverse scaling
    * If scaling is 200% and I move the cursor to P _on-screen_, the actual point where color is picked is at 2P, origin at top-left corner.

**Comment by tjohnman** [comment]
I'd like to add that, regarding the animation/preview viewport on the top right, the zoom slider gets messed up and unworkable when using UI scaling.

**Comment by OverloadedOrama** [comment]
Seems to be fixed in version 1.0. Feel free to re-open the issue if you still experience these issues.
