### ISSUE TITLE
Supporting MacOS hotkeys

### ISSUE THREAD

**Issue by AndreevAndrei** [Orama-Interactive/Pixelorama#67]
It's not very comfortable to use Ctrl+* to shortcut in MacOS. It would be better if Pixelorama will support Cmd+*
_I'de like to fix it in this week_

**Comment by Calinou** [comment]
I think it should be as easy as replacing all instances of `KEY_MASK_CTRL` with `KEY_MASK_CMD` in scripts :slightly_smiling_face:

**Comment by AndreevAndrei** [comment]
yeap, it's realy easy, just a few fixes
now it's comfortable to use on macOS)

**Comment by OverloadedOrama** [comment]
The issue shouldn't be closed yet because, like Calinou said, `Control+C` and `Control+V` are still being used for copy&pasting, and since I'm on a Windows machine, I don't know if I can re-assign them to use Command instead.

**Comment by OverloadedOrama** [comment]
Taking a look inside `project.godot`, it seems that both "control" and "command" are `true` on copy and paste. Can you check to see if they're working?

**Comment by AndreevAndrei** [comment]
at current settings I need to hold `control + command + c` to copy

**Comment by gingerbeardman** [comment]
I'm sure we all are aware, but I wanted to mention this is till an issue with 0.8.1 for any people new to this thread

**Comment by Schweini07** [comment]
I think the fix for this is add to seperate key actions in the input menu.
Like this:
`save_key`
- ctrl + s
- command + s

I tried it on a mac and it seems to work, I'll look at it tomorrow and probably open a PR.

**Comment by Schweini07** [comment]
Sadly a false alarm.
It seems the order in which those actions are listed are important.
I had it like that:
`save_key`
- command  + s
- ctrl +s

In this case `ctrl+s`doesn't works.
