### ISSUE TITLE
Rotating image by multiples of 90 degrees is broken.

### ISSUE THREAD

**Issue by yaboy365** [Orama-Interactive/Pixelorama#675]
**Pixelorama version:**

0.10

**Issue description:**

Images rotated by 90, 180 and 270 degrees, are not correct pixelwise.

**Steps to reproduce:**
The issue is visible in the provided project. There are 2 triangles, both rotated clockwise by 90 degrees. Red, with pixelorama, and green, with Ubuntu's image viewer, with both results in separate layers. The triangles are made, so that the whole image should be covered, yet there are gaps in the red portion of the image.

I guess a simple override with a separate rotating function for those 3 rotations would fix it.

Also, I think the "Rotate Image" menu could be improved with 5 buttons for quicker use. These would be -90, -45, 0, +45, +90, with 0 setting the rotation degrees back to 0. This could be great for making top-down spritesheets quickly, and the addition of multiples of 45 degrees would be an improvement over the image viewer. But that's just my suggestion.

**Comment by Variable-ind** [comment]
Hy👋, Pixelorama allows user to use one of 3 different algorithms (whatever suits the user) for image rotation. Do all three have this problem?

**Comment by yaboy365** [comment]
Yes.

**Comment by Variable-ind** [comment]
I tried to fix some things regarding rotation [HERE](https://nightly.link/Orama-Interactive/Pixelorama/actions/runs/2215210188). Could you try and tell me if the issue is fixed? (use the "`upscale, rotate and downscale`" algorithm)
