### ISSUE TITLE
Android version

### ISSUE THREAD

**Issue by axredneck** [Orama-Interactive/Pixelorama#68]
Is it possible to port Pixelorama to Android?

**Comment by Calinou** [comment]
This is likely feasible from a technical standpoint, but the UI isn't designed to be used on a small screen.

**Comment by axredneck** [comment]
Screen is not small of it's a tablet.

**Comment by Calinou** [comment]
@axredneck In this case, it still has to be designed to be used with a touchscreen rather than a keyboard and mouse :slightly_smiling_face:

This implies buttons need to be larger, among other things.

**Comment by OverloadedOrama** [comment]
I actually did some Android experiments yesterday. The UI is indeed very small, but I think this can be fixed. Not sure how but we would eventually figure it out. The real issue is the FileDialog nodes. No matter how much I've tried, I can't open and/or save files in Android.

**Comment by AndreevAndrei** [comment]
And it need to support a stylus (stick) for Samsung Galaxy Nodes 🤣 
Or morden iPad sticks)

**Comment by axredneck** [comment]
@OverloadedOrama does it have a permission to save files?

**Comment by OverloadedOrama** [comment]
> @OverloadedOrama does it have a permission to save files?

It's been a while since I last tested it, but last time I checked I did give permission to save and load files. I think they're the "Read External Storage" and "Write External Storage" permissions found in Godot's Android export settings.
