### ISSUE TITLE
No way of auto adjusting pallete height whille changing width of pallete and vice-versa.

### ISSUE THREAD

**Issue by yuyutsupoudel** [Orama-Interactive/Pixelorama#684]
Height should auto adjust while changing width of palette and vice versa so that colors are not lost or have to manually count number of colors, calculate the height based upon selected width and place the height. This is just a extra step of inconvenience but still having a way of not deleting your colors accidentally would be a nice feature.

Version:
0.10 stable  Linux build
**Steps to reproduce:**
try to adjust width or height of a large palette with out loosing colors.

**Comment by OverloadedOrama** [comment]
This should be fixed by b6583e4133f4e6ecf1cb4b916336640e10be4d32, the fix will be available on version 1.0.1.
