### ISSUE TITLE
Cursor for RMB tool

### ISSUE THREAD

**Issue by yaboy365** [Orama-Interactive/Pixelorama#691]
In addition to the blue cursor for the LMB tool, I think a secondary orange cursor for the RMB tool, would improve using both simultaneously. For example, when using a 1px pencil with 3px eraser, it's hard to tell, what's actually going to be erased, especially with different brushes.

**Comment by mrtripie** [comment]
There is setting for that already - Edit > Preferences > Cursors > Right pixel indicator. Though, I think the indicators for each tool should match the blue/orange color scheme in the toolbar and have both enabled by default.

**Comment by yaboy365** [comment]
Damn, my bad. My point about color coding still stands though.
