### ISSUE TITLE
Mirror view issues

### ISSUE THREAD

**Issue by Oni-93** [Orama-Interactive/Pixelorama#717]
**Pixelorama version:**

V0.10.1 stable

**OS/device including version:**

Arch 5.18.11 AMD A8-7650K Radeon R7

**Issue description:**

There are some things that don't work when mirror view is enabled. On this 3 videos, i first show how it behaves normally and then how it behaves on mirror view.
- [ ] Select tools don't show the handles for transform operations.

https://user-images.githubusercontent.com/104327699/179374446-18f554d4-19de-4f3a-aa6d-ed8435f23ca2.mp4

- [ ] Shape tools don't show the preview correctly.

https://user-images.githubusercontent.com/104327699/179374482-5f4db1c4-f5b7-484a-b187-1a22c19da8e0.mp4

- [x] Onion skin shows old preview (fixed in 2e795e8db50a9f83549a0b28dfb4c2b58c242ea2)

https://user-images.githubusercontent.com/104327699/179374504-a543fb60-031e-4691-ad9c-dd1a808b2efc.mp4

**Steps to reproduce:**
Show on video

**Comment by Variable-ind** [comment]
> Shape tools don't show the preview correctly.
This bug was also in lasso and ellipse tools

i've created #860 that aims to fix the remaining two issues
