### ISSUE TITLE
Release 0.10.1 Pixelorama.Mac.dmg updated 9 days ago.

### ISSUE THREAD

**Issue by zachauten** [Orama-Interactive/Pixelorama#732]
**Pixelorama version:**

**OS/device including version:**

**Issue description:**

It looks like 9 days ago, the release asset for the Mac was updated for version 0.10.1. Previously the checksum for Pixelorama.Mac.dmg was `f70457cec53c65d732995bc52dea42daa43af08bf4f49cca965d95bfa14bf931`, now it is `eb7cc92ca887f1751e62681409472502d337059417de762d09226ccee839248e`. I couldn't find record of CI that triggered the change, or any issues or prs relating to why the Mac build would have been changed. The change broke the installation process in homebrew, so I just wanted some clarification before opening a pr to fix it there.

**Steps to reproduce:**
You can see in the release page that the binary for macOS was updated more recently than other platforms.

**Comment by OverloadedOrama** [comment]
I changed the build as a hotfix for #718. The previous build was unusable because it crashed immediately.

**Comment by zachauten** [comment]
Thanks for the info!
