### ISSUE TITLE
Typo: Cel or Cell?

### ISSUE THREAD

**Issue by libreajans** [Orama-Interactive/Pixelorama#748]
**Pixelorama version:**
0.10.2 from Flatpak

**OS/device including version:**
Ubuntu 22.04.1 Linux

**Issue description:**
There are several typos.

Current cel > Current cell
Link Cel > Link Cell
Unlink Cel > Unlink Cell
Enable/disable cel linking > Enable/disable cell linking
Linked cels are being shared across multiple frames > Linked cells are being shared across multiple frames
Selected cels > Selected cells

**Steps to reproduce:**
Check on source code

**Comment by OverloadedOrama** [comment]
These are not typos. The proper term is "Cel", which is short for ["celluloid"](http://en.wikipedia.org/wiki/Cel). For more information, you can refer to the relevant documentation page. https://www.oramainteractive.com/Pixelorama-Docs/concepts/cel
