### ISSUE TITLE
Onion skin settings don't save between runs

### ISSUE THREAD

**Issue by shinobody** [Orama-Interactive/Pixelorama#757]
**Pixelorama version:**
 v0.10-2 stable

**OS/device including version:**
 Windows 10
I put Pixelorama in a folder synced with Mega cloud drive, idk if it's related, I know Windows 10 can be pretty glitchy about cloud sync folders.

**Issue description:**
Changing onion settings does not save them after closing and restarting. Which is annoying, as I usually don't want to see future frames or see them 'above canvas' so I have to change them every time.

**Steps to reproduce:**
Change onion skin settings, restart program. Onion skin setting return to default (1 frame future, 1 frame back, both above canvas).

**Comment by bfedie518** [comment]
Confirmed in v.10.3 on Windows 10 without cloud syncing.  Onion skin settings to not persist after Pixelorama has been closed.
