### ISSUE TITLE
Changing the size of the circle selection shape doesn't look right

### ISSUE THREAD

**Issue by Dark-Peace** [Orama-Interactive/Pixelorama#774]
**Pixelorama version:**
Browser version on Itch.io

**OS/device including version:**
Browser version on Itch.io, using Google Chrome

**Issue description:**
When using the circle selection, and modifying it's scale through the tool menu, it doesn't scale properly the shape, instead it looks like it only expands the selection according to the first row/column. It also works for custom shape selection.

**Steps to reproduce:**
Use the circle shape selection, change the size with the tool menu on the right

![Capture d’écran (382)](https://user-images.githubusercontent.com/74102789/199329669-f31e99fb-78b7-4c0a-a4de-cf2117f2b6d6.png)

**Comment by MdeeDev** [comment]
It seems to work properly only if you apply the selection on something .
when this value is true
`is_moving_content`
 But when it is empty and not moving anything it behaves badly like that. Any clue?
