### ISSUE TITLE
UI problem

### ISSUE THREAD

**Issue by GamerBlue208** [Orama-Interactive/Pixelorama#775]
Pixelorama version:
Pixelorama v0.10.3-sable

Hardware:
OS: Linux/Ubuntu 3.28.2
GPU: AMD® Raven2
CPU: AMD® 3015e with Radeon Graphics × 4
Memory: 3,3 GiB

Issue:
The UI is really small, and the program is unusable, I tried reinstalling, and It's still broken.
![Captura de pantalla de 2022-11-02 11-18-52](https://user-images.githubusercontent.com/115688181/199468487-873b8613-1e41-46a1-b5e7-5cf11bbc4ac4.png)

**Comment by Variable-ind** [comment]
You can scale the UI by going to File>Preferences>Interface

**Comment by GamerBlue208** [comment]
> You can scale the UI by going to File>Preferences>Interface

Thks
