### ISSUE TITLE
Mac: Built-in palettes not found

### ISSUE THREAD

**Issue by zellyn** [Orama-Interactive/Pixelorama#791]
**Pixelorama version:**
0.10.3, both .dmg and homebrew

**OS/device including version:**
Mac M1 Max

**Issue description:**
The builtin palettes are not found in the UI

**Steps to reproduce:**
Install Pixelorama. Look at the dropdown in the Palettes menu. There are no palettes.

**Reason**

If you create a new palette, it is saved in `/Applications/Pixelorama.app/Contents/MacOS/pixelorama_data/Palettes`.
The included palettes are stored in `/Applications/Pixelorama.app/Contents/Resources/pixelorama_data/Palettes`.
If you copy the included palettes from `Resources` to `Contents/MacOS`, they show up in the UI.

**Comment by ivanquirino** [comment]
Same issue on Pixelorama version 0.11.3, mas OS 12.3, intel cpu

**Comment by haythamnikolaidis** [comment]
I am experiencing the same problem, MacOS 13.1, intel CPU, version 0.11.4 a quick check and it looks like on a fresh install the `pixelorama_data` folder is not found in the in the `Contents/MacOS` folder at all this means, that the default patterns, brushes and palettes do not load.

My initial attempt to work around this, I downloaded the `pixelorama_data` folder from the main branch, to replace the missing folder, (they get created as empty on first run) this resolved the problem for the brushes and the patterns, but not the palettes, after stumbling upon the work around in this thread I realised that the palettes files in the main branch are `json` while the ones shipped with Pixelorama are `tres.` Replacing the `json` files with the `tres` ones resolves the problem for palettes.
