### ISSUE TITLE
Mistake about the translation of zh_CN

### ISSUE THREAD

**Issue by Mrsjh** [Orama-Interactive/Pixelorama#801]
**Pixelorama version:**

v0.10.3

**OS/device including version:**

Linux Mint 21.1

**Issue description:**

There is a mistake about the translation of zh_CN

**Steps to reproduce:**
Open your Pixelorama and look at the toolbar which is at the left of your window, the eighth one from the top which should be "放大镜" 
rather than "油漆桶" because there is already one below .

![zoom_mistake.png](https://i.imgaa.com/2023/01/01/63b18416eefd7311892152.png)
![bucket.png](https://i.imgaa.com/2023/01/01/63b1840028b15022433496.png)

**Comment by OverloadedOrama** [comment]
Thanks for reporting! I fixed the issue in Crowdin, and it will get fixed in Pixelorama once #756 is merged.
