### ISSUE TITLE
Split layers

### ISSUE THREAD

**Issue by ildar-in** [Orama-Interactive/Pixelorama#832]
### Discussed in https://github.com/Orama-Interactive/Pixelorama/discussions/831

<div type='discussions-op-text'>

<sup>Originally posted by **ildar-in** March  9, 2023</sup>
Export each layer separately. Full animation exports into folder, with individual ".png" file for each layer.
This feature exists in "Piskel App".
![image](https://user-images.githubusercontent.com/88928505/224097958-b992f7b6-f491-464a-8d0e-d7f1814af4a6.png)
</div>

**Comment by OverloadedOrama** [comment]
Closing this as #831 already exists.
