### ISSUE TITLE
Fixing "Parent node is busy setting up children, move_child() failed".

### ISSUE THREAD

**Issue by Sslaxx** [Orama-Interactive/Pixelorama#90]
This would be a pretty straightforward fix.

The offending line: `$QuitDialog.popup_centered()` (Main.gd, line 202 as of https://github.com/Orama-Interactive/Pixelorama/commit/1f2d8406c26ba06fc3d9341a512d022364c1c94e) (https://github.com/Orama-Interactive/Pixelorama/blob/master/Scripts/Main.gd#L202)

Fixed, per Godot's recommendation: `$QuitDialog.call_deferred ("popup_centered")`

Godot 3.1.2 flags it up as an error, despite the program still running, and it should not be assumed that it'd work as-is on future versions (or indeed, all platforms).

**Comment by OverloadedOrama** [comment]
Ah, I should've known the fix was so simple. Thank you!
