### ISSUE TITLE
`Bucket` tool to replace color (multiple frames), chance to mass up with wrong color

### ISSUE THREAD

**Issue by redyyu** [Orama-Interactive/Pixelorama#908]
**Pixelorama version:**
v0.11.2 (b2c157f)

**Issue description:**
Use `Bucket` tool to replace color, chance to mass up with wrong color, especially while multiple frames are selected.

most time fine, event color be massed with one frame. but when too many frames... will be nightmare to check and recheck each frame is correct.

**Steps to reproduce:**

select multiple frames, ex., 10 or 20 frames. (200frame total, maybe that cause the problem, not sure.)
Choose `Bucket` tool. in the buck tool option menu, select fill area to be `similar area` (with 100%), Fill with `selected color`.

**Comment by OverloadedOrama** [comment]
If I am understanding the issue correctly, this is fixed now in version 1.0 by 896d714a9e889b26978968873e3d9512b99ceffe.
