### ISSUE TITLE
default_env.tres is empty.

### ISSUE THREAD

**Issue by Sslaxx** [Orama-Interactive/Pixelorama#91]
As of https://github.com/Orama-Interactive/Pixelorama/commit/02f5bd0f5b8aacdd0a35785df5166f2b9dec91ca (and before this), running Pixelorama from Godot generates this error:
```
ERROR: recognize: res://default_env.tres:1 - Parse Error:
   At: scene/resources/resource_format_text.cpp:1186
```

This is because default_env.tres is an invalid file.

An example of what'd be valid file contents:
```
[gd_resource type="Environment" load_steps=2 format=2]

[sub_resource type="ProceduralSky" id=1]

[resource]
background_mode = 2
background_sky = SubResource( 1 )
```

As this appears only to be meaningful to 3D worldspaces, this has no visual impact on Pixelorama.

**Comment by OverloadedOrama** [comment]
Should it be deleted then? Will deleting it have any impact on the project, since it's not 3D?

**Comment by Sslaxx** [comment]
Removing it has no impact on the project.

**Comment by OverloadedOrama** [comment]
Okay, I'll remove it then. Thank you!
