### ISSUE TITLE
[AUR] Broken UI

### ISSUE THREAD

**Issue by 4194304** [Orama-Interactive/Pixelorama#912]
**Pixelorama version:**

Latest version from AUR

**OS/device including version:**

Arch Linux
GTX 1050 Ti, DKMS, proprietary

**Issue description:**

UI appears messed up and isn't functional. Clicking on the buttons on the top of the screen do nothing. All other buttons do nothing either. Opening things directly, ex. opening a png file with Pixelorama don't show the correct interface and will still show the exact same broken interface.

It should open as usual with no issues.

**Steps to reproduce:**
Unsure

**Screenshots:**
![image](https://github.com/Orama-Interactive/Pixelorama/assets/130800536/eb879c38-f98e-4a0a-84e8-a1b26acc407b)

**Comment by 4194304** [comment]
Occurs from the AUR, used the version from the itch.io page and it opened without errors. I'll keep this open for further investigation

**Comment by OverloadedOrama** [comment]
Closing as this seems to be an AUR issue, which is not maintained by us.
