### ISSUE TITLE
Pixelorama crash after trying rotate selection or image

### ISSUE THREAD

**Issue by DOGamedev5** [Orama-Interactive/Pixelorama#917]
OS: linux - Manjaro
CPU: intel I3 540 with gpu

**Issue description:**
pixelorama crash after selecting "rotate image" 

**Steps to reproduce:**
select an area of pixels with the rectangle selection tool, and then access the image -> rotate image

**Comment by Variable-ind** [comment]
hello :wave: which version of pixelorama are you using?

**Comment by Variable-ind** [comment]
> OS: linux - Manjaro CPU: intel I3 540 with gpu
> 
> **Issue description:** pixelorama crash after select "rotate image"
> 
> **Steps to reproduce:** select some pixels with rectangle select click in image - rotate image

if you are using an older version then it may have been fixed
https://github.com/Orama-Interactive/Pixelorama/commit/ad61ddc2c0c251e8e20da3369c072e48380c0cd3

**Comment by DOGamedev5** [comment]
> hello :wave: which version of pixelorama are you using?

the latest one i think, 0.11.2, but i dont have seeing if has newest version, so maybe i'm using 0.11.1

sorry for bad english

**Comment by Variable-ind** [comment]
> > hello 👋 which version of pixelorama are you using?
> 
> the latest one i think, 0.11.2, but i dont have seeing if has newest version, so maybe i'm using 0.11.1
> 
> sorry for bad english

does it also crash with small images (like 64x64)?
could you post the log file?

### steps:
1. click `help -->open logs folder` (a folder will open containing logs)
2. crash pixelorama
3. without re-opening pixelorama goto the folder (that you opened in step 1) and place the `godot.log` file here

**Comment by DOGamedev5** [comment]
> > > hello 👋 which version of pixelorama are you using?
> > 
> > 
> > the latest one i think, 0.11.2, but i dont have seeing if has newest version, so maybe i'm using 0.11.1
> > sorry for bad english
> 
> does it also crash with small images (like 64x64)? could you post the log file?
> ### steps:
> 
>     1. click `help -->open logs folder` (a folder will open containing logs, do not close it)
> 
>     2. crash pixelorama
> 
>     3. without re-opening pixelorama goto the folder (that you opened in step 1) and place the `godot.log` file here

yes, it crashes in 64x64 canvas too

[godot.log](https://github.com/Orama-Interactive/Pixelorama/files/12850849/godot.log)

**Comment by DOGamedev5** [comment]
updating here, recently I changed to distro linux mint and the problems continue to happen, I dont know if the issue its the amount of RAM of my pc (its 4 gb) or the gpu or whatever

**Comment by Variable-ind** [comment]
> updating here, recently I changed to distro linux mint and the problems continue to happen, I dont know if the issue its the amount of RAM of my pc (its 4 gb) or the gpu or whatever

The next version (currently in development) had some ram optimizations recently could you check the nightly build to see if it still happens?
https://nightly.link/Orama-Interactive/Pixelorama/workflows/dev-desktop-builds/0.x

**Comment by DOGamedev5** [comment]
> > updating here, recently I changed to distro linux mint and the problems continue to happen, I dont know if the issue its the amount of RAM of my pc (its 4 gb) or the gpu or whatever
> 
> The next version (currently in development) had some ram optimizations recently could you check the nightly build to see if it still happens?
> https://nightly.link/Orama-Interactive/Pixelorama/workflows/dev-desktop-builds/0.x

sure, when I come home I will test, thanks for help

(sorry for bad english)

**Comment by DOGamedev5** [comment]
the problem still happening

there is the godot.log, if that help
[godot.log](https://github.com/Orama-Interactive/Pixelorama/files/13492372/godot.log)

and I find this other file, I thing he can help more
[godot2023-11-28T16.27.59.log](https://github.com/Orama-Interactive/Pixelorama/files/13492381/godot2023-11-28T16.27.59.log)

**Comment by DOGamedev5** [comment]
problem apparently stopped happening, I don't know if it was an OS or pixelorama update

**Comment by Variable-ind** [comment]
Nice, not sure how but I'm glad it got fixed. Thanks again for your continued feedback 😁
