### ISSUE TITLE
Shading Tool breaks Undo functionality

### ISSUE THREAD

**Issue by alexmi1** [Orama-Interactive/Pixelorama#923]
**Pixelorama version:**
v0.11.2-stable

**OS/device including version:**
KDE Neon 5.27 (Linux)

**Issue description:**
After using the Shading tool and changing to another tool, Undo/Redo does not work properly.

**Steps to reproduce:**
1. Select the Shading tool
2. Paint on the canvas
3. Select any other tool
4. Try to Undo. An "Undo: Draw" message appears, but the canvas does not get reverted.

**Comment by Variable-ind** [comment]
Thanks for reporting. This bug will be fixed in the next version (0.11.3)

**Comment by OverloadedOrama** [comment]
Fixed by 331c46c8eeed694b724dc0f18dcf56411654d049 (and #916 for 0.x)
