### ISSUE TITLE
Top of window blurry on MacOS Retina Display

### ISSUE THREAD

**Issue by Togira123** [Orama-Interactive/Pixelorama#936]
**Pixelorama version:**
0.11.3

**OS/device including version:**
MacOS Sonoma 14.1 MacBook Pro 14-inch 2023

**Issue description:**
The top bar of the application where the three buttons are to either maximise, minimise or close the window is blurry. View image below.
<img width="920" alt="Screenshot 2023-11-05 at 4 45 55 PM" src="https://github.com/Orama-Interactive/Pixelorama/assets/70365614/a76a546a-f584-4ea3-b758-b3011ef60e07">

**Steps to reproduce:**
Download Pixelorama on a Mac and open the application. You'll notice the very top of the window being blurry.

**Comment by Togira123** [comment]
I think I have identified the issue! After cloning the repository and building the Pixelorama from source, I noticed that everything looks fine but when I untick the "High Res" option when exporting, it looks blurry, just like in the actual build.
<img width="501" alt="Screenshot 2023-11-08 at 2 47 58 PM" src="https://github.com/Orama-Interactive/Pixelorama/assets/70365614/b2fa3d0c-d1f9-41ed-8adb-127e1c4f7557">
If that option is enabled it would probably look fine :)

**Comment by OverloadedOrama** [comment]
Thank you for reporting and identifying the issue. As the "High Res" option is enabled by default on the master branch, the issue can be considered resolved. I am not sure why it wasn't enabled by default on Godot 3.x, but I went ahead and enabled it on the 0.x branch too, so the fix will be available in version 0.11.4.
