### ISSUE TITLE
Program can sometimes crash when resizing images

### ISSUE THREAD

**Issue by 4194304** [Orama-Interactive/Pixelorama#948]
**Pixelorama version:**

0.11.2-stable

**OS/device including version:**

Arch Linux (latest) with KDE Plasma

**Issue description:**

When resizing images, the program can sometimes crash without warning. It doesn't always work, but it happens around 1/4 times when doing this.

**Steps to reproduce:**
1. Import a random image
2. Scale it down to a different size with the select tool
3. Try to crop it to the area that you shrunk it down to.
4. The program can crash

**Comment by 4194304** [comment]
I also had the crash occur when I was using the dedicated scaling tool, but I noticed that it's a lot rarer.

**Comment by OverloadedOrama** [comment]
Does this still occur with version 1.0?

**Comment by 4194304** [comment]
Have not tested it

**Comment by 4194304** [comment]
I resized a random image MANY times over and over (probably around 11 times), and thankfully I did not experience a crash, so this can be closed for now (unless it comes back to bite me at a later date!)
