### ISSUE TITLE
Pixelorama Crashes when run from the Godot Editor 

### ISSUE THREAD

**Issue by TheLsbt** [Orama-Interactive/Pixelorama#960]
**Pixelorama version:**

#959

**OS/device including version:**

Issue is not related to graphics.

**Issue description:**

When running Pixelorama for source in **Godot 4.2 stable** an error occurs on lines **690** and **698** in [**ExtensionsApi.gd**](https://github.com/Orama-Interactive/Pixelorama/raw/master/src/Autoload/ExtensionsApi.gd).
The functions expects 2 arguments however only one is passed. 
I have found a simple fix for this by passing **"ImportApi"** (following previous patterns) as the first arguments in these functions.
I haven't made a pull request with the changes because I am waiting on @Variable-ind's response as I'm not sure how important those arguments are.

**Steps to reproduce:**
Run the Pixelorama #959  in **Godot 4.2 stable**

**Comment by hormigas** [comment]
Looks like they just need to add a name. Changing 
690
`		ExtensionsApi.add_action("ImportAPI", "add_import_option")`

and 698 to 

`		ExtensionsApi.remove_action("ImportAPI","add_import_option")`

removes the issue. I based the name on the previous name for the exporter.

**Comment by Variable-ind** [comment]
this fix will be added some time today or tomorrow by @OverloadedOrama :grin:
