### ISSUE TITLE
Tar.gz inside zip

### ISSUE THREAD

**Issue by caarfken** [Orama-Interactive/Pixelorama#975]
**Pixelorama version:**
0.11.3

**OS/device including version:**
Linux x86-64

**Issue description:**
When I downloaded Pixelorama, I got a zip file containing a tar.gz file
Expected results:
I would get a zip file containing a folder, as is usually the case

**Steps to reproduce:**
Download the Linux x86-64 version.

**Comment by Variable-ind** [comment]
yeah, it's normal, for linux (64 bit) there is a zip file inside which is a tar.gz file. you need to extract both to get the executable.

**Comment by OverloadedOrama** [comment]
This is a known issue with GitHub, waiting for them to fix it on their end. https://github.com/actions/upload-artifact/issues/39

**Comment by caarfken** [comment]
Should I close the issue, then?

**Comment by OverloadedOrama** [comment]
> Should I close the issue, then?

Yeah I think so, there's not much we can do until GitHub fixes the issue.
