### ISSUE TITLE
File won't open either save!

### ISSUE THREAD

**Issue by Heloooh** [Orama-Interactive/Pixelorama#981]
**Pixelorama version:**
v0.11

**Issue description:**
I tried to open a Pixelorama file that I had saved and selected the ALWAYS open with Pixelorama option, but now it won't open any more projects and I can't save either. It shows this error when I try to open: Couldn't load project data in path ".". Is the .pck file missing?

I need help :(

**Steps to reproduce:**
1 - Save the project as .pxo;
2 - Click to open on the files and select "always open with Pixelorama"

**Comment by OverloadedOrama** [comment]
Is the `Pixelorama.pck` file in the same folder as the Pixelorama executable?

**Comment by Heloooh** [comment]
> Is the `Pixelorama.pck` file in the same folder as the Pixelorama executable?
I don't know, how can I see it?

**Comment by OverloadedOrama** [comment]
You can locate the folder where you unzipped Pixelorama when you first downloaded it. Or if you used the Windows installer, I think it should be located somewhere in Program Files. Check if that folder contains both the executable (Pixelorama.exe on Windows, Pixelorama.x86_64 on Linux) and Pixelorama.pck. If they aren't in the same folder then Pixelorama will fail to run, which is what the error you're getting is saying. If you're having trouble, you can re-download Pixelorama. v0.11 is an outdated version anyway, v0.11.3 is the newest one.

Also please provide more information in your bug reports, such as your operating system, so we can identify the problem more easily.

**Comment by Heloooh** [comment]
> You can locate the folder where you unzipped Pixelorama when you first downloaded it. Or if you used the Windows installer, I think it should be located somewhere in Program Files. Check if that folder contains both the executable (Pixelorama.exe on Windows, Pixelorama.x86_64 on Linux) and Pixelorama.pck. If they aren't in the same folder then Pixelorama will fail to run, which is what the error you're getting is saying. If you're having trouble, you can re-download Pixelorama. v0.11 is an outdated version anyway, v0.11.3 is the newest one.
> 
> Also please provide more information in your bug reports, such as your operating system, so we can identify the problem more easily.

It worked!! Thank you so much!! :>
(Ok, I'll improve my reports and update my Pixelorama too)

**Comment by OverloadedOrama** [comment]
Glad it worked! I'll close this issue as resolved then! :)
