### ISSUE TITLE
My project doesn't want to load

### ISSUE THREAD

**Issue by Heloooh** [Orama-Interactive/Pixelorama#985]
**Pixelorama version:**
v0.11

**OS/device including version:**
Windows 10 Pro - Version: 22H2

**Issue description:**
I accidentally shut down my pc and closed the program with a project I didn't save. When I log in again, the message to load the project appears, but when I click "Ok" Pixelorama closes :(

**Steps to reproduce:**
1 - Create a project;
2 - Close the app without saving it;
3 - Open the app again and try to open the project.

**Comment by OverloadedOrama** [comment]
Hello! I'm not sure I understand the issue. How do you open a project that has not been saved? Are you referring to the backup system? I tested both v0.11 and v0.11.3 (latest stable version) with the backup system and the autosaved projects seem to be opening normally. Is there any error that appears before Pixelorama closes? If not, could you please upload the log files (instructions how to find them can be found here https://www.oramainteractive.com/Pixelorama-Docs/troubleshooting#pixelorama-crashed-while-i-was-working-on-my-project), in case any messages appear there?

**Comment by Heloooh** [comment]
> Hello! I'm not sure I understand the issue. How do you open a project that has not been saved? Are you referring to the backup system? I tested both v0.11 and v0.11.3 (latest stable version) with the backup system and the autosaved projects seem to be opening normally. Is there any error that appears before Pixelorama closes? If not, could you please upload the log files (instructions how to find them can be found here https://www.oramainteractive.com/Pixelorama-Docs/troubleshooting#pixelorama-crashed-while-i-was-working-on-my-project), in case any messages appear there?

Hello! Yeah, Pixelorama wasn't opening the backup so I gave up on recovering the file and created a new project...But now I'm having another problem, when I try to open a project that I saved, the app closes! I don't know if the problem is my PC, which may not support the project... Would there be a way to send the project and have someone save it in png?

**Comment by Variable-ind** [comment]
> , w

Hello 👋, You can compress the pxo as a zip file (GitHub accepts the zip file)

**Comment by Heloooh** [comment]
[h_hud.zip](https://github.com/Orama-Interactive/Pixelorama/files/14496018/h_hud.zip)

Hello! Thank you, next time I will save it as ZSTD. The file is as zip, can you save in png for me?

**Comment by OverloadedOrama** [comment]
Unfortunately it seems like that pxo file is corrupt, for some reason, sorry. Not sure how and why this happened, and I am not sure if the data can be recovered, unless you have a backup. Version 1.0 changes the file format of pxo files to be .zip files in disguise, hopefully this format will be harder to end up corrupted.

**Comment by Heloooh** [comment]
Okay, thx for the help :)

**Comment by fime-space** [comment]
Ended up having the same issue for some reason, my file was corrupted and this was causing pixelorama to crash at startup because it was trying to load it .... annoying ToT anyway great job on the editor now let's redraw ...

**Comment by OverloadedOrama** [comment]
Closing as the file format of .pxo files has changed in version 1.0, so this issue may have been resolved now. Feel free to open a new issue if you encounter corrupted .pxo files in version 1.0.
